/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "fx_ble_msg.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(DataPackage, DataPackage, 2)


PB_BIND(ConnectPro, ConnectPro, AUTO)


PB_BIND(ServicePro, ServicePro, AUTO)


PB_BIND(SupportData, SupportData, AUTO)


PB_BIND(CommandPro, CommandPro, 2)


PB_BIND(TimeSync, TimeSync, AUTO)


PB_BIND(DeviceInfo, DeviceInfo, 2)


PB_BIND(DebugInfo, DebugInfo, AUTO)


PB_BIND(DeviceInfoValue, DeviceInfoValue, AUTO)


PB_BIND(DebugInfoValue, DebugInfoValue, AUTO)


PB_BIND(ModelInfo, ModelInfo, AUTO)


PB_BIND(SnInfo, SnInfo, AUTO)


PB_BIND(DeviceRemind, DeviceRemind, AUTO)


PB_BIND(BrushingReport, BrushingReport, 2)


PB_BIND(ReportData, ReportData, 2)


PB_BIND(UserInfo, UserInfo, AUTO)


PB_BIND(UserThemeInfo, UserThemeInfo, 2)


PB_BIND(AlgorithmPro, AlgorithmPro, AUTO)


PB_BIND(AlgorithmRealTime, AlgorithmRealTime, 2)


PB_BIND(AlgorithmReport, AlgorithmReport, 2)


PB_BIND(SimpleReport, SimpleReport, AUTO)


PB_BIND(FillBrushData, FillBrushData, AUTO)


PB_BIND(RemindResult, RemindResult, AUTO)


PB_BIND(RemindSingleResult, RemindSingleResult, AUTO)


PB_BIND(AlgorithmRemind, AlgorithmRemind, 2)


PB_BIND(AlgorithmCollect, AlgorithmCollect, AUTO)


PB_BIND(WifiInfo, WifiInfo, AUTO)


PB_BIND(DeviceStateInfo, DeviceStateInfo, AUTO)


PB_BIND(CustomButtonInfo, CustomButtonInfo, 2)


PB_BIND(CustomButtonContent, CustomButtonContent, AUTO)


PB_BIND(DeviceState, DeviceState, AUTO)


PB_BIND(DeviceValue, DeviceValue, AUTO)


PB_BIND(FrequencyBand, FrequencyBand, AUTO)


PB_BIND(Temperature, Temperature, AUTO)


PB_BIND(DeviceUp, DeviceUp, AUTO)


PB_BIND(DeviceRemindInfo, DeviceRemindInfo, AUTO)


PB_BIND(DeviceReport, DeviceReport, AUTO)


PB_BIND(VideoReportData, VideoReportData, AUTO)


PB_BIND(AudioDataInfo, AudioDataInfo, 2)


PB_BIND(RotasFileStatusReq, RotasFileStatusReq, AUTO)


PB_BIND(RotasFileStatusRsp, RotasFileStatusRsp, AUTO)


PB_BIND(RotasDataReq, RotasDataReq, AUTO)


PB_BIND(RotasDataRsp, RotasDataRsp, AUTO)


PB_BIND(RotasResultReq, RotasResultReq, AUTO)


PB_BIND(RotasResultRsp, RotasResultRsp, AUTO)


PB_BIND(PlanInfo, PlanInfo, 2)


PB_BIND(RecommendInfo, RecommendInfo, 2)


PB_BIND(PlanModelInfo, PlanModelInfo, AUTO)


PB_BIND(CustomPlanGroupInfo, CustomPlanGroupInfo, 2)





















































