/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef PB_SERVER_DATA_PB_H_INCLUDED
#define PB_SERVER_DATA_PB_H_INCLUDED
#include <pb.h>
#include "fx_ble_msg.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _RequestType { 
    RequestType_GET = 0, 
    RequestType_POST = 1, 
    RequestType_PUT = 2, 
    RequestType_DELETE = 3, 
    RequestType_PATCH = 4 
} RequestType;

/* Struct definitions */
typedef struct _UsGiftDetailVO { 
    pb_callback_t us_gift_detail_list; 
} UsGiftDetailVO;

typedef struct _AudioDataOption { 
    pb_callback_t name; 
    bool has_audio_data_info;
    AudioDataInfo audio_data_info; 
    char preview_file_url[256]; 
    char preview_img_file_url[256]; 
} AudioDataOption;

typedef struct _CustomGroupOption { 
    char name[32]; 
    bool has_group_info;
    CustomPlanGroupInfo group_info; 
} CustomGroupOption;

typedef struct _FileInfo { 
    uint32_t file_id; 
    char file_url[256]; 
    uint32_t file_size; 
    char file_md5[64]; 
} FileInfo;

typedef struct _MetaData { 
    uint32_t version_type; 
    uint32_t version_code; 
    char url[128]; 
    char md5[64]; 
    uint32_t size; 
} MetaData;

typedef struct _RequestParam { 
    pb_size_t which_request_param;
    union {
        char user_id[64];
        char device_id[64];
        uint32_t connect_type;
    } request_param; 
} RequestParam;

typedef struct _Setting { 
    uint32_t setting_id; 
    /* Connect Service 0x10 */
    pb_size_t which_setting_data;
    union {
        DeviceInfo get_device_info;
        DeviceStateInfo device_state_set;
        CustomButtonInfo get_custom_button_info;
        UserThemeInfo get_user_theme_info;
        AlgorithmPro algorithm_pro;
        AudioDataInfo get_audio_info;
        PlanInfo get_plan_info;
        RecommendInfo get_recommend_info;
        CustomPlanGroupInfo get_custom_group_info;
    } setting_data; /* 0x06 */
} Setting;

typedef struct _UsGiftDetail { 
    uint32_t id; 
    pb_callback_t sender_meb_id; 
    pb_callback_t sender_nickname; 
    pb_callback_t receiver_phone; 
    uint32_t model_id; 
    uint32_t theme_detail_id; 
    uint32_t status; 
    uint32_t file_id; 
} UsGiftDetail;

typedef struct _UserGiftInfoVO { 
    pb_size_t gift_info_list_count;
    UserThemeInfo gift_info_list[2]; 
    bool isGetGift; 
} UserGiftInfoVO;

typedef struct _UserThemeOption { 
    char name[32]; 
    bool has_user_theme_info;
    UserThemeInfo user_theme_info; 
    char preview_img_file_url[256]; 
} UserThemeOption;

typedef struct _AudioDataInfoVO { 
    pb_size_t audio_option_list_count;
    AudioDataOption audio_option_list[2]; 
} AudioDataInfoVO;

typedef struct _CustomPlanGroupInfoVO { 
    pb_size_t option_list_count;
    CustomGroupOption option_list[5]; 
} CustomPlanGroupInfoVO;

typedef struct _OtaUpdateInfo { 
    char device_id[64]; 
    uint32_t hardware_id; 
    uint32_t model_id; 
    uint32_t version_code; 
    uint32_t version_type; 
    uint32_t firmware_id; 
    uint32_t version_code_min; 
    uint32_t version_code_max; 
    pb_size_t meta_data_count;
    MetaData meta_data[6]; 
} OtaUpdateInfo;

typedef struct _SettingVO { 
    pb_size_t setting_list_count;
    Setting setting_list[3]; 
} SettingVO;

typedef struct _UserThemeInfoVO { 
    pb_size_t theme_info_list_count;
    UserThemeOption theme_info_list[2]; 
} UserThemeInfoVO;

/* /请求服务器参数 */
typedef struct _RequestPackage { 
    char request_url[128]; 
    RequestType request_type; 
    pb_size_t request_param_count;
    RequestParam request_param[3]; 
    pb_size_t which_request_data;
    union {
        WifiInfo upload_wifi_info;
        BrushingReport upload_brush_report;
        SettingVO setting_vo;
        ConnectPro upload_connect_pro;
        OtaUpdateInfo upload_ota_info;
        CustomButtonInfo upload_custom_button_info;
        AudioDataInfoVO audio_info_vo;
        RecommendInfo upload_recommend_info;
        CustomPlanGroupInfoVO group_info_vo;
        UserThemeInfoVO theme_info_vo;
        UserGiftInfoVO gift_theme_info;
        FileInfo file_info;
        UsGiftDetail us_gift_detail;
    } request_data; 
} RequestPackage;

/* /服务器返回数据 */
typedef struct _ResponsePackage { 
    bool flag; 
    uint32_t code; 
    char message[128]; 
    pb_size_t which_response_data;
    union {
        WifiInfo get_wifi_info;
        BrushingReport upload_brush_report;
        SettingVO setting_vo;
        ConnectPro upload_connect_pro;
        OtaUpdateInfo upload_ota_info;
        CustomButtonInfo upload_custom_button_info;
        AudioDataInfoVO audio_info_vo;
        RecommendInfo upload_recommend_info;
        CustomPlanGroupInfoVO group_info_vo;
        UserThemeInfoVO theme_info_vo;
        UserGiftInfoVO gift_theme_info;
        FileInfo file_info;
        UsGiftDetail us_gift_detail;
    } response_data; 
} ResponsePackage;


/* Helper constants for enums */
#define _RequestType_MIN RequestType_GET
#define _RequestType_MAX RequestType_PATCH
#define _RequestType_ARRAYSIZE ((RequestType)(RequestType_PATCH+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define RequestPackage_init_default              {"", _RequestType_MIN, 0, {RequestParam_init_default, RequestParam_init_default, RequestParam_init_default}, 0, {WifiInfo_init_default}}
#define ResponsePackage_init_default             {0, 0, "", 0, {WifiInfo_init_default}}
#define UsGiftDetailVO_init_default              {{{NULL}, NULL}}
#define UsGiftDetail_init_default                {0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0, 0}
#define FileInfo_init_default                    {0, "", 0, ""}
#define UserGiftInfoVO_init_default              {0, {UserThemeInfo_init_default, UserThemeInfo_init_default}, 0}
#define UserThemeInfoVO_init_default             {0, {UserThemeOption_init_default, UserThemeOption_init_default}}
#define UserThemeOption_init_default             {"", false, UserThemeInfo_init_default, ""}
#define AudioDataInfoVO_init_default             {0, {AudioDataOption_init_default, AudioDataOption_init_default}}
#define AudioDataOption_init_default             {{{NULL}, NULL}, false, AudioDataInfo_init_default, "", ""}
#define CustomPlanGroupInfoVO_init_default       {0, {CustomGroupOption_init_default, CustomGroupOption_init_default, CustomGroupOption_init_default, CustomGroupOption_init_default, CustomGroupOption_init_default}}
#define CustomGroupOption_init_default           {"", false, CustomPlanGroupInfo_init_default}
#define SettingVO_init_default                   {0, {Setting_init_default, Setting_init_default, Setting_init_default}}
#define Setting_init_default                     {0, 0, {DeviceInfo_init_default}}
#define RequestParam_init_default                {0, {""}}
#define OtaUpdateInfo_init_default               {"", 0, 0, 0, 0, 0, 0, 0, 0, {MetaData_init_default, MetaData_init_default, MetaData_init_default, MetaData_init_default, MetaData_init_default, MetaData_init_default}}
#define MetaData_init_default                    {0, 0, "", "", 0}
#define RequestPackage_init_zero                 {"", _RequestType_MIN, 0, {RequestParam_init_zero, RequestParam_init_zero, RequestParam_init_zero}, 0, {WifiInfo_init_zero}}
#define ResponsePackage_init_zero                {0, 0, "", 0, {WifiInfo_init_zero}}
#define UsGiftDetailVO_init_zero                 {{{NULL}, NULL}}
#define UsGiftDetail_init_zero                   {0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0, 0}
#define FileInfo_init_zero                       {0, "", 0, ""}
#define UserGiftInfoVO_init_zero                 {0, {UserThemeInfo_init_zero, UserThemeInfo_init_zero}, 0}
#define UserThemeInfoVO_init_zero                {0, {UserThemeOption_init_zero, UserThemeOption_init_zero}}
#define UserThemeOption_init_zero                {"", false, UserThemeInfo_init_zero, ""}
#define AudioDataInfoVO_init_zero                {0, {AudioDataOption_init_zero, AudioDataOption_init_zero}}
#define AudioDataOption_init_zero                {{{NULL}, NULL}, false, AudioDataInfo_init_zero, "", ""}
#define CustomPlanGroupInfoVO_init_zero          {0, {CustomGroupOption_init_zero, CustomGroupOption_init_zero, CustomGroupOption_init_zero, CustomGroupOption_init_zero, CustomGroupOption_init_zero}}
#define CustomGroupOption_init_zero              {"", false, CustomPlanGroupInfo_init_zero}
#define SettingVO_init_zero                      {0, {Setting_init_zero, Setting_init_zero, Setting_init_zero}}
#define Setting_init_zero                        {0, 0, {DeviceInfo_init_zero}}
#define RequestParam_init_zero                   {0, {""}}
#define OtaUpdateInfo_init_zero                  {"", 0, 0, 0, 0, 0, 0, 0, 0, {MetaData_init_zero, MetaData_init_zero, MetaData_init_zero, MetaData_init_zero, MetaData_init_zero, MetaData_init_zero}}
#define MetaData_init_zero                       {0, 0, "", "", 0}

/* Field tags (for use in manual encoding/decoding) */
#define UsGiftDetailVO_us_gift_detail_list_tag   1
#define AudioDataOption_name_tag                 1
#define AudioDataOption_audio_data_info_tag      2
#define AudioDataOption_preview_file_url_tag     3
#define AudioDataOption_preview_img_file_url_tag 4
#define CustomGroupOption_name_tag               1
#define CustomGroupOption_group_info_tag         2
#define FileInfo_file_id_tag                     1
#define FileInfo_file_url_tag                    2
#define FileInfo_file_size_tag                   3
#define FileInfo_file_md5_tag                    4
#define MetaData_version_type_tag                1
#define MetaData_version_code_tag                2
#define MetaData_url_tag                         3
#define MetaData_md5_tag                         4
#define MetaData_size_tag                        5
#define RequestParam_user_id_tag                 1
#define RequestParam_device_id_tag               2
#define RequestParam_connect_type_tag            3
#define Setting_setting_id_tag                   1
#define Setting_get_device_info_tag              7
#define Setting_device_state_set_tag             15
#define Setting_get_custom_button_info_tag       17
#define Setting_get_user_theme_info_tag          35
#define Setting_algorithm_pro_tag                49
#define Setting_get_audio_info_tag               70
#define Setting_get_plan_info_tag                113
#define Setting_get_recommend_info_tag           115
#define Setting_get_custom_group_info_tag        117
#define UsGiftDetail_id_tag                      1
#define UsGiftDetail_sender_meb_id_tag           2
#define UsGiftDetail_sender_nickname_tag         3
#define UsGiftDetail_receiver_phone_tag          4
#define UsGiftDetail_model_id_tag                5
#define UsGiftDetail_theme_detail_id_tag         6
#define UsGiftDetail_status_tag                  7
#define UsGiftDetail_file_id_tag                 8
#define UserGiftInfoVO_gift_info_list_tag        1
#define UserGiftInfoVO_isGetGift_tag             2
#define UserThemeOption_name_tag                 1
#define UserThemeOption_user_theme_info_tag      2
#define UserThemeOption_preview_img_file_url_tag 3
#define AudioDataInfoVO_audio_option_list_tag    1
#define CustomPlanGroupInfoVO_option_list_tag    1
#define OtaUpdateInfo_device_id_tag              1
#define OtaUpdateInfo_hardware_id_tag            2
#define OtaUpdateInfo_model_id_tag               3
#define OtaUpdateInfo_version_code_tag           4
#define OtaUpdateInfo_version_type_tag           5
#define OtaUpdateInfo_firmware_id_tag            6
#define OtaUpdateInfo_version_code_min_tag       7
#define OtaUpdateInfo_version_code_max_tag       8
#define OtaUpdateInfo_meta_data_tag              100
#define SettingVO_setting_list_tag               1
#define UserThemeInfoVO_theme_info_list_tag      1
#define RequestPackage_request_url_tag           1
#define RequestPackage_request_type_tag          2
#define RequestPackage_request_param_tag         3
#define RequestPackage_upload_wifi_info_tag      101
#define RequestPackage_upload_brush_report_tag   102
#define RequestPackage_setting_vo_tag            103
#define RequestPackage_upload_connect_pro_tag    104
#define RequestPackage_upload_ota_info_tag       105
#define RequestPackage_upload_custom_button_info_tag 106
#define RequestPackage_audio_info_vo_tag         107
#define RequestPackage_upload_recommend_info_tag 108
#define RequestPackage_group_info_vo_tag         109
#define RequestPackage_theme_info_vo_tag         110
#define RequestPackage_gift_theme_info_tag       111
#define RequestPackage_file_info_tag             112
#define RequestPackage_us_gift_detail_tag        113
#define ResponsePackage_flag_tag                 1
#define ResponsePackage_code_tag                 2
#define ResponsePackage_message_tag              3
#define ResponsePackage_get_wifi_info_tag        101
#define ResponsePackage_upload_brush_report_tag  102
#define ResponsePackage_setting_vo_tag           103
#define ResponsePackage_upload_connect_pro_tag   104
#define ResponsePackage_upload_ota_info_tag      105
#define ResponsePackage_upload_custom_button_info_tag 106
#define ResponsePackage_audio_info_vo_tag        107
#define ResponsePackage_upload_recommend_info_tag 108
#define ResponsePackage_group_info_vo_tag        109
#define ResponsePackage_theme_info_vo_tag        110
#define ResponsePackage_gift_theme_info_tag      111
#define ResponsePackage_file_info_tag            112
#define ResponsePackage_us_gift_detail_tag       113

/* Struct field encoding specification for nanopb */
#define RequestPackage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   request_url,       1) \
X(a, STATIC,   SINGULAR, UENUM,    request_type,      2) \
X(a, STATIC,   REPEATED, MESSAGE,  request_param,     3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request_data,upload_wifi_info,request_data.upload_wifi_info), 101) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request_data,upload_brush_report,request_data.upload_brush_report), 102) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request_data,setting_vo,request_data.setting_vo), 103) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request_data,upload_connect_pro,request_data.upload_connect_pro), 104) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request_data,upload_ota_info,request_data.upload_ota_info), 105) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request_data,upload_custom_button_info,request_data.upload_custom_button_info), 106) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request_data,audio_info_vo,request_data.audio_info_vo), 107) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request_data,upload_recommend_info,request_data.upload_recommend_info), 108) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request_data,group_info_vo,request_data.group_info_vo), 109) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request_data,theme_info_vo,request_data.theme_info_vo), 110) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request_data,gift_theme_info,request_data.gift_theme_info), 111) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request_data,file_info,request_data.file_info), 112) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request_data,us_gift_detail,request_data.us_gift_detail), 113)
#define RequestPackage_CALLBACK NULL
#define RequestPackage_DEFAULT NULL
#define RequestPackage_request_param_MSGTYPE RequestParam
#define RequestPackage_request_data_upload_wifi_info_MSGTYPE WifiInfo
#define RequestPackage_request_data_upload_brush_report_MSGTYPE BrushingReport
#define RequestPackage_request_data_setting_vo_MSGTYPE SettingVO
#define RequestPackage_request_data_upload_connect_pro_MSGTYPE ConnectPro
#define RequestPackage_request_data_upload_ota_info_MSGTYPE OtaUpdateInfo
#define RequestPackage_request_data_upload_custom_button_info_MSGTYPE CustomButtonInfo
#define RequestPackage_request_data_audio_info_vo_MSGTYPE AudioDataInfoVO
#define RequestPackage_request_data_upload_recommend_info_MSGTYPE RecommendInfo
#define RequestPackage_request_data_group_info_vo_MSGTYPE CustomPlanGroupInfoVO
#define RequestPackage_request_data_theme_info_vo_MSGTYPE UserThemeInfoVO
#define RequestPackage_request_data_gift_theme_info_MSGTYPE UserGiftInfoVO
#define RequestPackage_request_data_file_info_MSGTYPE FileInfo
#define RequestPackage_request_data_us_gift_detail_MSGTYPE UsGiftDetail

#define ResponsePackage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     flag,              1) \
X(a, STATIC,   SINGULAR, UINT32,   code,              2) \
X(a, STATIC,   SINGULAR, STRING,   message,           3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response_data,get_wifi_info,response_data.get_wifi_info), 101) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response_data,upload_brush_report,response_data.upload_brush_report), 102) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response_data,setting_vo,response_data.setting_vo), 103) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response_data,upload_connect_pro,response_data.upload_connect_pro), 104) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response_data,upload_ota_info,response_data.upload_ota_info), 105) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response_data,upload_custom_button_info,response_data.upload_custom_button_info), 106) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response_data,audio_info_vo,response_data.audio_info_vo), 107) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response_data,upload_recommend_info,response_data.upload_recommend_info), 108) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response_data,group_info_vo,response_data.group_info_vo), 109) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response_data,theme_info_vo,response_data.theme_info_vo), 110) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response_data,gift_theme_info,response_data.gift_theme_info), 111) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response_data,file_info,response_data.file_info), 112) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response_data,us_gift_detail,response_data.us_gift_detail), 113)
#define ResponsePackage_CALLBACK NULL
#define ResponsePackage_DEFAULT NULL
#define ResponsePackage_response_data_get_wifi_info_MSGTYPE WifiInfo
#define ResponsePackage_response_data_upload_brush_report_MSGTYPE BrushingReport
#define ResponsePackage_response_data_setting_vo_MSGTYPE SettingVO
#define ResponsePackage_response_data_upload_connect_pro_MSGTYPE ConnectPro
#define ResponsePackage_response_data_upload_ota_info_MSGTYPE OtaUpdateInfo
#define ResponsePackage_response_data_upload_custom_button_info_MSGTYPE CustomButtonInfo
#define ResponsePackage_response_data_audio_info_vo_MSGTYPE AudioDataInfoVO
#define ResponsePackage_response_data_upload_recommend_info_MSGTYPE RecommendInfo
#define ResponsePackage_response_data_group_info_vo_MSGTYPE CustomPlanGroupInfoVO
#define ResponsePackage_response_data_theme_info_vo_MSGTYPE UserThemeInfoVO
#define ResponsePackage_response_data_gift_theme_info_MSGTYPE UserGiftInfoVO
#define ResponsePackage_response_data_file_info_MSGTYPE FileInfo
#define ResponsePackage_response_data_us_gift_detail_MSGTYPE UsGiftDetail

#define UsGiftDetailVO_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  us_gift_detail_list,   1)
#define UsGiftDetailVO_CALLBACK pb_default_field_callback
#define UsGiftDetailVO_DEFAULT NULL
#define UsGiftDetailVO_us_gift_detail_list_MSGTYPE UsGiftDetail

#define UsGiftDetail_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                1) \
X(a, CALLBACK, SINGULAR, STRING,   sender_meb_id,     2) \
X(a, CALLBACK, SINGULAR, STRING,   sender_nickname,   3) \
X(a, CALLBACK, SINGULAR, STRING,   receiver_phone,    4) \
X(a, STATIC,   SINGULAR, UINT32,   model_id,          5) \
X(a, STATIC,   SINGULAR, UINT32,   theme_detail_id,   6) \
X(a, STATIC,   SINGULAR, UINT32,   status,            7) \
X(a, STATIC,   SINGULAR, UINT32,   file_id,           8)
#define UsGiftDetail_CALLBACK pb_default_field_callback
#define UsGiftDetail_DEFAULT NULL

#define FileInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   file_id,           1) \
X(a, STATIC,   SINGULAR, STRING,   file_url,          2) \
X(a, STATIC,   SINGULAR, UINT32,   file_size,         3) \
X(a, STATIC,   SINGULAR, STRING,   file_md5,          4)
#define FileInfo_CALLBACK NULL
#define FileInfo_DEFAULT NULL

#define UserGiftInfoVO_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  gift_info_list,    1) \
X(a, STATIC,   SINGULAR, BOOL,     isGetGift,         2)
#define UserGiftInfoVO_CALLBACK NULL
#define UserGiftInfoVO_DEFAULT NULL
#define UserGiftInfoVO_gift_info_list_MSGTYPE UserThemeInfo

#define UserThemeInfoVO_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  theme_info_list,   1)
#define UserThemeInfoVO_CALLBACK NULL
#define UserThemeInfoVO_DEFAULT NULL
#define UserThemeInfoVO_theme_info_list_MSGTYPE UserThemeOption

#define UserThemeOption_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   name,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  user_theme_info,   2) \
X(a, STATIC,   SINGULAR, STRING,   preview_img_file_url,   3)
#define UserThemeOption_CALLBACK NULL
#define UserThemeOption_DEFAULT NULL
#define UserThemeOption_user_theme_info_MSGTYPE UserThemeInfo

#define AudioDataInfoVO_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  audio_option_list,   1)
#define AudioDataInfoVO_CALLBACK NULL
#define AudioDataInfoVO_DEFAULT NULL
#define AudioDataInfoVO_audio_option_list_MSGTYPE AudioDataOption

#define AudioDataOption_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  audio_data_info,   2) \
X(a, STATIC,   SINGULAR, STRING,   preview_file_url,   3) \
X(a, STATIC,   SINGULAR, STRING,   preview_img_file_url,   4)
#define AudioDataOption_CALLBACK pb_default_field_callback
#define AudioDataOption_DEFAULT NULL
#define AudioDataOption_audio_data_info_MSGTYPE AudioDataInfo

#define CustomPlanGroupInfoVO_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  option_list,       1)
#define CustomPlanGroupInfoVO_CALLBACK NULL
#define CustomPlanGroupInfoVO_DEFAULT NULL
#define CustomPlanGroupInfoVO_option_list_MSGTYPE CustomGroupOption

#define CustomGroupOption_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   name,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  group_info,        2)
#define CustomGroupOption_CALLBACK NULL
#define CustomGroupOption_DEFAULT NULL
#define CustomGroupOption_group_info_MSGTYPE CustomPlanGroupInfo

#define SettingVO_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  setting_list,      1)
#define SettingVO_CALLBACK NULL
#define SettingVO_DEFAULT NULL
#define SettingVO_setting_list_MSGTYPE Setting

#define Setting_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   setting_id,        1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (setting_data,get_device_info,setting_data.get_device_info),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (setting_data,device_state_set,setting_data.device_state_set),  15) \
X(a, STATIC,   ONEOF,    MESSAGE,  (setting_data,get_custom_button_info,setting_data.get_custom_button_info),  17) \
X(a, STATIC,   ONEOF,    MESSAGE,  (setting_data,get_user_theme_info,setting_data.get_user_theme_info),  35) \
X(a, STATIC,   ONEOF,    MESSAGE,  (setting_data,algorithm_pro,setting_data.algorithm_pro),  49) \
X(a, STATIC,   ONEOF,    MESSAGE,  (setting_data,get_audio_info,setting_data.get_audio_info),  70) \
X(a, STATIC,   ONEOF,    MESSAGE,  (setting_data,get_plan_info,setting_data.get_plan_info), 113) \
X(a, STATIC,   ONEOF,    MESSAGE,  (setting_data,get_recommend_info,setting_data.get_recommend_info), 115) \
X(a, STATIC,   ONEOF,    MESSAGE,  (setting_data,get_custom_group_info,setting_data.get_custom_group_info), 117)
#define Setting_CALLBACK NULL
#define Setting_DEFAULT NULL
#define Setting_setting_data_get_device_info_MSGTYPE DeviceInfo
#define Setting_setting_data_device_state_set_MSGTYPE DeviceStateInfo
#define Setting_setting_data_get_custom_button_info_MSGTYPE CustomButtonInfo
#define Setting_setting_data_get_user_theme_info_MSGTYPE UserThemeInfo
#define Setting_setting_data_algorithm_pro_MSGTYPE AlgorithmPro
#define Setting_setting_data_get_audio_info_MSGTYPE AudioDataInfo
#define Setting_setting_data_get_plan_info_MSGTYPE PlanInfo
#define Setting_setting_data_get_recommend_info_MSGTYPE RecommendInfo
#define Setting_setting_data_get_custom_group_info_MSGTYPE CustomPlanGroupInfo

#define RequestParam_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    STRING,   (request_param,user_id,request_param.user_id),   1) \
X(a, STATIC,   ONEOF,    STRING,   (request_param,device_id,request_param.device_id),   2) \
X(a, STATIC,   ONEOF,    UINT32,   (request_param,connect_type,request_param.connect_type),   3)
#define RequestParam_CALLBACK NULL
#define RequestParam_DEFAULT NULL

#define OtaUpdateInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   device_id,         1) \
X(a, STATIC,   SINGULAR, UINT32,   hardware_id,       2) \
X(a, STATIC,   SINGULAR, UINT32,   model_id,          3) \
X(a, STATIC,   SINGULAR, UINT32,   version_code,      4) \
X(a, STATIC,   SINGULAR, UINT32,   version_type,      5) \
X(a, STATIC,   SINGULAR, UINT32,   firmware_id,       6) \
X(a, STATIC,   SINGULAR, UINT32,   version_code_min,   7) \
X(a, STATIC,   SINGULAR, UINT32,   version_code_max,   8) \
X(a, STATIC,   REPEATED, MESSAGE,  meta_data,       100)
#define OtaUpdateInfo_CALLBACK NULL
#define OtaUpdateInfo_DEFAULT NULL
#define OtaUpdateInfo_meta_data_MSGTYPE MetaData

#define MetaData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   version_type,      1) \
X(a, STATIC,   SINGULAR, UINT32,   version_code,      2) \
X(a, STATIC,   SINGULAR, STRING,   url,               3) \
X(a, STATIC,   SINGULAR, STRING,   md5,               4) \
X(a, STATIC,   SINGULAR, UINT32,   size,              5)
#define MetaData_CALLBACK NULL
#define MetaData_DEFAULT NULL

extern const pb_msgdesc_t RequestPackage_msg;
extern const pb_msgdesc_t ResponsePackage_msg;
extern const pb_msgdesc_t UsGiftDetailVO_msg;
extern const pb_msgdesc_t UsGiftDetail_msg;
extern const pb_msgdesc_t FileInfo_msg;
extern const pb_msgdesc_t UserGiftInfoVO_msg;
extern const pb_msgdesc_t UserThemeInfoVO_msg;
extern const pb_msgdesc_t UserThemeOption_msg;
extern const pb_msgdesc_t AudioDataInfoVO_msg;
extern const pb_msgdesc_t AudioDataOption_msg;
extern const pb_msgdesc_t CustomPlanGroupInfoVO_msg;
extern const pb_msgdesc_t CustomGroupOption_msg;
extern const pb_msgdesc_t SettingVO_msg;
extern const pb_msgdesc_t Setting_msg;
extern const pb_msgdesc_t RequestParam_msg;
extern const pb_msgdesc_t OtaUpdateInfo_msg;
extern const pb_msgdesc_t MetaData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define RequestPackage_fields &RequestPackage_msg
#define ResponsePackage_fields &ResponsePackage_msg
#define UsGiftDetailVO_fields &UsGiftDetailVO_msg
#define UsGiftDetail_fields &UsGiftDetail_msg
#define FileInfo_fields &FileInfo_msg
#define UserGiftInfoVO_fields &UserGiftInfoVO_msg
#define UserThemeInfoVO_fields &UserThemeInfoVO_msg
#define UserThemeOption_fields &UserThemeOption_msg
#define AudioDataInfoVO_fields &AudioDataInfoVO_msg
#define AudioDataOption_fields &AudioDataOption_msg
#define CustomPlanGroupInfoVO_fields &CustomPlanGroupInfoVO_msg
#define CustomGroupOption_fields &CustomGroupOption_msg
#define SettingVO_fields &SettingVO_msg
#define Setting_fields &Setting_msg
#define RequestParam_fields &RequestParam_msg
#define OtaUpdateInfo_fields &OtaUpdateInfo_msg
#define MetaData_fields &MetaData_msg

/* Maximum encoded size of messages (where known) */
/* RequestPackage_size depends on runtime parameters */
/* ResponsePackage_size depends on runtime parameters */
/* UsGiftDetailVO_size depends on runtime parameters */
/* UsGiftDetail_size depends on runtime parameters */
/* AudioDataInfoVO_size depends on runtime parameters */
/* AudioDataOption_size depends on runtime parameters */
#define CustomGroupOption_size                   221
#define CustomPlanGroupInfoVO_size               1120
#define FileInfo_size                            335
#define MetaData_size                            213
#define OtaUpdateInfo_size                       1409
#define RequestParam_size                        65
#define SettingVO_size                           1122
#define Setting_size                             371
#define UserGiftInfoVO_size                      132
#define UserThemeInfoVO_size                     718
#define UserThemeOption_size                     356

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
