/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef PB_DATA_COLLECTION_PB_H_INCLUDED
#define PB_DATA_COLLECTION_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _DebugFileType { 
    DebugFileType_UNKNOWN_FILE_TYPE = 0, 
    DebugFileType_DATA_LOG = 1, 
    DebugFileType_DATA_CAMERA = 2 
} DebugFileType;

typedef enum _FileStatus { 
    FileStatus_DATA_START = 0, 
    FileStatus_DATA_PAUSE = 1, 
    FileStatus_DATA_STOP = 2, 
    FileStatus_DATA_RESET = 3, 
    FileStatus_DATA_FORCE_START = 4 
} FileStatus;

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(240) DebugDataReq_data_t;
typedef struct _DebugDataReq { 
    DebugFileType fileType; 
    uint32_t index; 
    DebugDataReq_data_t data; 
} DebugDataReq;

typedef struct _DebugFileStatus { 
    FileStatus rotaStatus; 
    DebugFileType fileType; 
} DebugFileStatus;


/* Helper constants for enums */
#define _DebugFileType_MIN DebugFileType_UNKNOWN_FILE_TYPE
#define _DebugFileType_MAX DebugFileType_DATA_CAMERA
#define _DebugFileType_ARRAYSIZE ((DebugFileType)(DebugFileType_DATA_CAMERA+1))

#define _FileStatus_MIN FileStatus_DATA_START
#define _FileStatus_MAX FileStatus_DATA_FORCE_START
#define _FileStatus_ARRAYSIZE ((FileStatus)(FileStatus_DATA_FORCE_START+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define DebugFileStatus_init_default             {_FileStatus_MIN, _DebugFileType_MIN}
#define DebugDataReq_init_default                {_DebugFileType_MIN, 0, {0, {0}}}
#define DebugFileStatus_init_zero                {_FileStatus_MIN, _DebugFileType_MIN}
#define DebugDataReq_init_zero                   {_DebugFileType_MIN, 0, {0, {0}}}

/* Field tags (for use in manual encoding/decoding) */
#define DebugDataReq_fileType_tag                1
#define DebugDataReq_index_tag                   2
#define DebugDataReq_data_tag                    3
#define DebugFileStatus_rotaStatus_tag           1
#define DebugFileStatus_fileType_tag             2

/* Struct field encoding specification for nanopb */
#define DebugFileStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    rotaStatus,        1) \
X(a, STATIC,   SINGULAR, UENUM,    fileType,          2)
#define DebugFileStatus_CALLBACK NULL
#define DebugFileStatus_DEFAULT NULL

#define DebugDataReq_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    fileType,          1) \
X(a, STATIC,   SINGULAR, UINT32,   index,             2) \
X(a, STATIC,   SINGULAR, BYTES,    data,              3)
#define DebugDataReq_CALLBACK NULL
#define DebugDataReq_DEFAULT NULL

extern const pb_msgdesc_t DebugFileStatus_msg;
extern const pb_msgdesc_t DebugDataReq_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define DebugFileStatus_fields &DebugFileStatus_msg
#define DebugDataReq_fields &DebugDataReq_msg

/* Maximum encoded size of messages (where known) */
#define DebugDataReq_size                        251
#define DebugFileStatus_size                     4

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
