# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_collection.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x64\x61ta_collection.proto\x1a\x0cnanopb.proto\"T\n\x0f\x44\x65\x62ugFileStatus\x12\x1f\n\nrotaStatus\x18\x01 \x01(\x0e\x32\x0b.FileStatus\x12 \n\x08\x66ileType\x18\x02 \x01(\x0e\x32\x0e.DebugFileType\"U\n\x0c\x44\x65\x62ugDataReq\x12 \n\x08\x66ileType\x18\x01 \x01(\x0e\x32\x0e.DebugFileType\x12\r\n\x05index\x18\x02 \x01(\r\x12\x14\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x42\x06\x92?\x03\x08\xf0\x01*E\n\rDebugFileType\x12\x15\n\x11UNKNOWN_FILE_TYPE\x10\x00\x12\x0c\n\x08\x44\x41TA_LOG\x10\x01\x12\x0f\n\x0b\x44\x41TA_CAMERA\x10\x02*a\n\nFileStatus\x12\x0e\n\nDATA_START\x10\x00\x12\x0e\n\nDATA_PAUSE\x10\x01\x12\r\n\tDATA_STOP\x10\x02\x12\x0e\n\nDATA_RESET\x10\x03\x12\x14\n\x10\x44\x41TA_FORCE_START\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_collection_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DEBUGDATAREQ'].fields_by_name['data']._options = None
  _globals['_DEBUGDATAREQ'].fields_by_name['data']._serialized_options = b'\222?\003\010\360\001'
  _globals['_DEBUGFILETYPE']._serialized_start=212
  _globals['_DEBUGFILETYPE']._serialized_end=281
  _globals['_FILESTATUS']._serialized_start=283
  _globals['_FILESTATUS']._serialized_end=380
  _globals['_DEBUGFILESTATUS']._serialized_start=39
  _globals['_DEBUGFILESTATUS']._serialized_end=123
  _globals['_DEBUGDATAREQ']._serialized_start=125
  _globals['_DEBUGDATAREQ']._serialized_end=210
# @@protoc_insertion_point(module_scope)
