/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "server_data.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(RequestPackage, RequestPackage, 2)


PB_BIND(SensorData, SensorData, AUTO)


PB_BIND(ResponsePackage, ResponsePackage, 2)


PB_BIND(UsGiftDetailVO, UsGiftDetailVO, AUTO)


PB_BIND(UsGiftDetail, UsGiftDetail, AUTO)


PB_BIND(FileInfo, FileInfo, 2)


PB_BIND(UserGiftInfoVO, UserGiftInfoVO, AUTO)


PB_BIND(UserThemeInfoVO, UserThemeInfoVO, 2)


PB_BIND(UserThemeOption, UserThemeOption, 2)


PB_BIND(AudioDataInfoVO, AudioDataInfoVO, 2)


PB_BIND(AudioDataOption, AudioDataOption, 2)


PB_BIND(CustomPlanGroupInfoVO, CustomPlanGroupInfoVO, 2)


PB_BIND(CustomGroupOption, CustomGroupOption, AUTO)


PB_BIND(SettingVO, SettingVO, 2)


PB_BIND(Setting, Setting, 2)


PB_BIND(RequestParam, RequestParam, AUTO)


PB_BIND(ResponseParam, ResponseParam, AUTO)


PB_BIND(OtaUpdateInfo, OtaUpdateInfo, 2)


PB_BIND(MetaData, MetaData, AUTO)


PB_BIND(DeviceLog, DeviceLog, AUTO)


PB_BIND(ProfessionalModelInfoVO, ProfessionalModelInfoVO, AUTO)


PB_BIND(LightCustomInfoVO, LightCustomInfoVO, 2)


PB_BIND(LightCustomOption, LightCustomOption, 2)


PB_BIND(PushConfigVO, PushConfigVO, AUTO)


PB_BIND(PushConfig, PushConfig, 2)


PB_BIND(EventTrackVO, EventTrackVO, AUTO)


PB_BIND(EventTrackInfo, EventTrackInfo, AUTO)




