/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "factory_msg.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(FactoryDataPackage, FactoryDataPackage, 2)


PB_BIND(FacGetDevBaseInfo, FacGetDevBaseInfo, 2)


PB_BIND(FacDevState, FacDevState, 2)


PB_BIND(FacBatteryInfo, FacBatteryInfo, AUTO)


PB_BIND(FacWifiInfo, FacWifiInfo, AUTO)


PB_BIND(FacDevInfoValue, FacDevInfoValue, AUTO)


PB_BIND(FacDevInfo, FacDevInfo, 2)


PB_BIND(FacGetPeriphState, FacGetPeriphState, 2)


PB_BIND(FacAgeingTest, FacAgeingTest, 2)


PB_BIND(FacRegisterConfig, FacRegisterConfig, AUTO)


PB_BIND(FacLcdControl, FacLcdControl, 2)


PB_BIND(FacMotoParam, FacMotoParam, AUTO)


PB_BIND(ServoMotorParam, ServoMotorParam, AUTO)


PB_BIND(FacMotoControl, FacMotoControl, 2)


PB_BIND(FacMotorCalibResult, FacMotorCalibResult, 2)


PB_BIND(FacCameraControl, FacCameraControl, 2)


PB_BIND(FacLedColor, FacLedColor, AUTO)


PB_BIND(FacLedControl, FacLedControl, 2)


PB_BIND(FacBrushControl, FacBrushControl, 2)


PB_BIND(DataCollectParam, DataCollectParam, AUTO)


PB_BIND(FacDataCollectItem, FacDataCollectItem, AUTO)


PB_BIND(FacCollectParam, FacCollectParam, 2)


PB_BIND(DataButtonParam, DataButtonParam, AUTO)


PB_BIND(FacButtonItem, FacButtonItem, AUTO)


PB_BIND(FacButtonState, FacButtonState, 2)


PB_BIND(FacWifiDemand, FacWifiDemand, 2)


PB_BIND(NineAlexData, NineAlexData, AUTO)


PB_BIND(FacUploadNineAlex, FacUploadNineAlex, 2)


PB_BIND(PresurceSensorItem, PresurceSensorItem, AUTO)


PB_BIND(PresurceSensorData, PresurceSensorData, AUTO)


PB_BIND(FacUploadPresSensor, FacUploadPresSensor, 2)


PB_BIND(FacPreSensorCalibResult, FacPreSensorCalibResult, 2)


PB_BIND(AccCaliData, AccCaliData, AUTO)


PB_BIND(FacImuCalibResult, FacImuCalibResult, 2)


PB_BIND(FacSetTime, FacSetTime, AUTO)


PB_BIND(FacSetBrushRecord, FacSetBrushRecord, AUTO)


PB_BIND(FacOtaFileInfo, FacOtaFileInfo, 2)


PB_BIND(FacInternetOta, FacInternetOta, 2)





















