/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef PB_FACTORY_MSG_PB_H_INCLUDED
#define PB_FACTORY_MSG_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _FacErrorCode { 
    FacErrorCode_NO_ERROR = 0, 
    FacErrorCode_NO_SUPPORT = 1, 
    FacErrorCode_NO_MEMORY = 2, 
    FacErrorCode_GENERALLY = 3 
} FacErrorCode;

typedef enum _FactroyCmd { 
    FactroyCmd_FIRST_COMMAND_NO_USE = 0, 
    FactroyCmd_GET_DEVICE_BASE_INFO = 1, 
    FactroyCmd_SET_DEVICE_STATE = 2, 
    FactroyCmd_GET_DEVICE_STATE = 3, 
    FactroyCmd_GET_PERIPH_STATE = 4, 
    FactroyCmd_SET_DEVICE_INFO = 5, 
    FactroyCmd_GET_DEVICE_INFO = 6, 
    FactroyCmd_SET_COLLECT_PARAM = 16, 
    FactroyCmd_GET_COLLECT_PARAM = 17, 
    FactroyCmd_UPLOAD_PRESS_SENSOR = 19, 
    FactroyCmd_UPLOAD_NINE_ALEX = 20, 
    FactroyCmd_GET_BUTTON_STATE = 21, 
    FactroyCmd_UPLOAD_BUTTON_STATE = 22, 
    FactroyCmd_UPLOAD_MOTORCALI_DATA = 23, 
    FactroyCmd_SET_PRESS_SENSOR_CALIB = 32, 
    FactroyCmd_GET_PRESS_SENSOR_CALIB = 33, 
    FactroyCmd_SET_IMU_CALIB = 34, 
    FactroyCmd_GET_IMU_CALIB = 35, 
    FactroyCmd_LED_CONTROL = 36, 
    FactroyCmd_LCD_CONTROL = 37, 
    FactroyCmd_MOTO_CONTROL = 38, 
    FactroyCmd_BRUSH_CONTROL = 39, 
    FactroyCmd_SET_TIME = 40, 
    FactroyCmd_CAMERA_CONTROL = 41, 
    FactroyCmd_SET_AGEING_TEST = 50, 
    FactroyCmd_SET_BRUSH_RECORD = 51, 
    FactroyCmd_WIFI_DEMAND = 52, 
    FactroyCmd_INTERNET_OTA = 64 
} FactroyCmd;

typedef enum _FacProtoId { 
    FacProtoId_PROTOCOL_NONE = 0, 
    FacProtoId_V1000 = 1000 
} FacProtoId;

typedef enum _DevStateType { 
    DevStateType_REBOOT = 0, 
    DevStateType_RESET = 1, 
    DevStateType_SLEEP = 2, 
    DevStateType_FORBID_SLEEP = 3, 
    DevStateType_FACTORY_QRCORD = 4, 
    DevStateType_SHIP = 5 
} DevStateType;

typedef enum _FacSwitch { 
    FacSwitch_STOP = 0, 
    FacSwitch_CLOSE = 0, 
    FacSwitch_START = 1, 
    FacSwitch_OPEN = 1 
} FacSwitch;

typedef enum _FacDevInfoType { 
    FacDevInfoType_WIFI_INFO = 0, 
    FacDevInfoType_TAIL_SN = 1, 
    FacDevInfoType_BOARD_SN = 2, 
    FacDevInfoType_BRUSH_MODE = 3, 
    FacDevInfoType_BATTERY_INFO = 4, 
    FacDevInfoType_IF_QUALIFIED = 5 
} FacDevInfoType;

typedef enum _FacChargeStateType { 
    FacChargeStateType_ERROR = 0, 
    FacChargeStateType_FULL = 1, 
    FacChargeStateType_CHARGING = 2, 
    FacChargeStateType_UNCHARGE = 3, 
    FacChargeStateType_NO_BATT = 4 
} FacChargeStateType;

typedef enum _FacAgeingTestType { 
    FacAgeingTestType_AGEING_1 = 0, 
    FacAgeingTestType_AGEING_2 = 1, 
    FacAgeingTestType_AGEING_3 = 2, 
    FacAgeingTestType_AGEING_4 = 3, 
    FacAgeingTestType_AGEING_PRODUCTION_1 = 4 
} FacAgeingTestType;

typedef enum _FacLcdControlType { 
    FacLcdControlType_color = 0, 
    FacLcdControlType_reg = 1 
} FacLcdControlType;

typedef enum _FacMotoControlType { 
    FacMotoControlType_motor_state = 0, 
    FacMotoControlType_motor_param = 1, 
    FacMotoControlType_play_file = 2, 
    FacMotoControlType_motor_cali = 3, 
    FacMotoControlType_motor_test = 4, 
    FacMotoControlType_damping_state = 5, 
    FacMotoControlType_motor_cali_data = 6, 
    FacMotoControlType_servo_param = 7 
} FacMotoControlType;

typedef enum _FacMotoCali { 
    FacMotoCali_HALL_CALIBRATION = 0, 
    FacMotoCali_ZERO_CALIBRATION = 1, 
    FacMotoCali_MOTOR_CALI_START = 2, 
    FacMotoCali_MOTOR_CALI_STOP = 3 
} FacMotoCali;

typedef enum _FacMotorUploadType { 
    FacMotorUploadType_HALL_CALIBRATION_DATA = 0, 
    FacMotorUploadType_ZERO_CALIBRATION_DATA = 1, 
    FacMotorUploadType_MOTOR_LOG = 2 
} FacMotorUploadType;

typedef enum _FacCameraControlType { 
    FacCameraControlType_camera_state = 0, 
    FacCameraControlType_camera_light = 1, 
    FacCameraControlType_camera_exposure_time = 2, 
    FacCameraControlType_camera_display_on_screen = 3, 
    FacCameraControlType_camera_support_state = 4, 
    FacCameraControlType_camera_get_picture = 5 
} FacCameraControlType;

typedef enum _LedPosition { 
    LedPosition_led_left_up = 0, 
    LedPosition_led_left_down = 1, 
    LedPosition_led_right_up = 2, 
    LedPosition_led_right_down = 3 
} LedPosition;

typedef enum _DataCollectType { 
    DataCollectType_BATTERY = 0, 
    DataCollectType_PRESSURE_SENSOR = 1, 
    DataCollectType_NINE_AXLE = 2 
} DataCollectType;

typedef enum _FacBrushControlType { 
    FacBrushControlType_BRUSH_START = 0, 
    FacBrushControlType_CHANGE_MODE = 1 
} FacBrushControlType;

typedef enum _FacButtonType { 
    FacButtonType_POWER_BUTTON = 0, 
    FacButtonType_MODEL_BUTTON = 1, 
    FacButtonType_PRESS_MECHANICAL = 2 
} FacButtonType;

typedef enum _ButtonState { 
    ButtonState_NULL = 0, 
    ButtonState_PRESSED = 1, 
    ButtonState_RELEASED = 2, 
    ButtonState_HELD = 3 
} ButtonState;

/* Struct definitions */
typedef struct _AccCaliData { 
    float kx; 
    float ky; 
    float kz; 
    float syx; 
    float szx; 
    float szy; 
    float bx; 
    float by; 
    float bz; 
} AccCaliData;

typedef struct _DataButtonParam { 
    FacSwitch state; 
    ButtonState button_state_now; /* 按键状态 */
} DataButtonParam;

typedef struct _DataCollectParam { 
    FacSwitch state; 
    uint32_t sampling_count; /* 采样次数  0xFFFFFFFF不限次数 */
    uint32_t sampling_rate; /* 采样率 */
    uint32_t upload_rate; /* 上报频率 */
} DataCollectParam;

typedef struct _FacAgeingTest { 
    FacAgeingTestType type; 
    FacSwitch switch_state; 
    uint32_t brush_mode; 
    uint32_t work_time; 
    uint32_t stop_time; 
    uint32_t cycle_count; 
    FacErrorCode result; 
} FacAgeingTest;

typedef struct _FacBatteryInfo { 
    FacChargeStateType charge_state; 
    uint32_t voltage; 
    uint32_t percent; 
} FacBatteryInfo;

typedef struct _FacBrushControl { 
    FacBrushControlType type; 
    pb_size_t which_value_item;
    union {
        FacSwitch brush_start;
        uint32_t change_mode;
    } value_item; 
    FacErrorCode result; 
} FacBrushControl;

typedef struct _FacCameraControl { 
    FacCameraControlType type; 
    pb_size_t which_value_item;
    union {
        FacSwitch camera_switch;
        FacSwitch light_switch;
        uint32_t exposure_time;
        FacSwitch display_on_screen;
        FacSwitch camera_support;
        FacSwitch get_picture;
    } value_item; 
    FacErrorCode result; 
} FacCameraControl;

typedef struct _FacDevState { 
    DevStateType dev_state_type; 
    FacSwitch state; 
    FacErrorCode result; 
} FacDevState;

typedef PB_BYTES_ARRAY_T(6) FacGetDevBaseInfo_ble_mac_t;
typedef PB_BYTES_ARRAY_T(6) FacGetDevBaseInfo_wifi_mac_t;
typedef struct _FacGetDevBaseInfo { 
    char product_name[8]; /* string */
    uint32_t pb_phone_ver; /* string */
    FacProtoId pb_factory_ver; /* string */
    char hw_version[4]; /* string */
    char soft_version[4]; /* string */
    char res_version[4]; /* string */
    char algo_version[4]; /* string */
    char presure_version[24]; 
    FacGetDevBaseInfo_ble_mac_t ble_mac; 
    FacGetDevBaseInfo_wifi_mac_t wifi_mac; 
    uint32_t imu_id; 
    bool ageing_state; 
    char motor_version[24]; 
    FacErrorCode result; 
} FacGetDevBaseInfo;

typedef struct _FacGetPeriphState { 
    bool imu_state; 
    bool flash_state; 
    bool magnet_state; 
    bool press_state; 
    bool audio_state; 
    FacErrorCode result; 
} FacGetPeriphState;

typedef struct _FacLedColor { 
    LedPosition index; 
    uint32_t R; 
    uint32_t G; 
    uint32_t B; 
} FacLedColor;

typedef struct _FacMotoParam { 
    uint32_t freq; 
    float gain_or_duty; 
    uint32_t volume; 
} FacMotoParam;

typedef struct _FacMotorCalibResult { 
    FacMotorUploadType type; 
    pb_size_t which_value_item;
    union {
        uint32_t hall_calibration_data;
        uint32_t zero_calibration_data;
        char motor_log[128];
    } value_item; 
    FacErrorCode result; 
} FacMotorCalibResult;

typedef struct _FacOtaFileInfo { 
    uint32_t file_size; 
    uint32_t version_code; /* 版本号 */
    uint32_t version_type; /* 文件类型  201固件  202资源  303音频 304主题 305音乐文件 */
    char url[256]; 
    char md5[64]; 
} FacOtaFileInfo;

typedef struct _FacPreSensorCalibResult { 
    uint32_t brush_head_adc; /* uint16 */
    uint32_t mode_button_adc; /* uint16 */
    uint32_t power_button_adc; 
    uint32_t temperature; 
    FacErrorCode result; 
} FacPreSensorCalibResult;

typedef struct _FacRegisterConfig { 
    uint32_t addr; 
    uint32_t value; 
} FacRegisterConfig;

typedef PB_BYTES_ARRAY_T(24) FacSetBrushRecord_work_time_t;
typedef PB_BYTES_ARRAY_T(12) FacSetBrushRecord_pressure_time_t;
typedef PB_BYTES_ARRAY_T(12) FacSetBrushRecord_horizon_brush_t;
typedef struct _FacSetBrushRecord { 
    uint32_t timestamp; 
    uint32_t plaque; /* 菌斑 */
    FacSetBrushRecord_work_time_t work_time; 
    FacSetBrushRecord_pressure_time_t pressure_time; 
    FacSetBrushRecord_horizon_brush_t horizon_brush; 
} FacSetBrushRecord;

typedef struct _FacSetTime { 
    uint32_t timestamp; 
    uint32_t timezone; 
} FacSetTime;

typedef PB_BYTES_ARRAY_T(4) FacWifiInfo_ip_address_t;
typedef struct _FacWifiInfo { 
    char wifi_name[32]; 
    char wifi_password[64]; 
    FacWifiInfo_ip_address_t ip_address; 
    uint32_t port; 
} FacWifiInfo;

typedef struct _NineAlexData { 
    uint32_t timestamp; 
    uint32_t acc_x; 
    uint32_t acc_y; 
    uint32_t acc_z; 
    uint32_t gyro_x; 
    uint32_t gyro_y; 
    uint32_t gyro_z; 
    uint32_t magnet_x; 
    uint32_t magnet_y; 
    uint32_t magnet_z; 
} NineAlexData;

typedef struct _PresurceSensorItem { 
    uint32_t adc; 
    uint32_t value; 
} PresurceSensorItem;

typedef struct _ServoMotorParam { 
    float vibrate_angle; 
    uint32_t sweeping_angle; 
    uint32_t vibrate_freq; 
    float sweeping_freq; 
} ServoMotorParam;

typedef struct _FacButtonItem { 
    FacButtonType type; 
    pb_size_t which_command_data;
    union {
        DataButtonParam power_button;
        DataButtonParam mode_button;
        DataButtonParam press_mechanical;
    } command_data; 
} FacButtonItem;

typedef struct _FacDataCollectItem { 
    DataCollectType type; 
    pb_size_t which_command_data;
    union {
        DataCollectParam bat_vol;
        DataCollectParam pressure_sensor;
        DataCollectParam nine_axle;
    } command_data; /* 电池电压 */
} FacDataCollectItem;

typedef struct _FacDevInfoValue { 
    FacDevInfoType info_item; 
    pb_size_t which_value_item;
    union {
        FacWifiInfo wifi_info;
        char tail_sn[64];
        char board_sn[64];
        uint32_t brush_mode;
        FacBatteryInfo battery;
        FacSwitch if_qualified;
    } value_item; 
} FacDevInfoValue;

typedef struct _FacImuCalibResult { 
    uint32_t gyro_x; 
    uint32_t gyro_y; 
    uint32_t gyro_z; 
    uint32_t acc_x; 
    uint32_t acc_y; 
    uint32_t acc_z; 
    bool has_new_cali;
    AccCaliData new_cali; 
    FacErrorCode result; 
} FacImuCalibResult;

typedef struct _FacInternetOta { 
    pb_size_t file_info_count;
    FacOtaFileInfo file_info[2]; 
    FacErrorCode result; 
} FacInternetOta;

typedef struct _FacLcdControl { 
    FacLcdControlType type; 
    pb_size_t which_value_item;
    union {
        uint32_t color;
        FacRegisterConfig config;
    } value_item; 
    FacErrorCode result; 
} FacLcdControl;

typedef struct _FacLedControl { 
    uint32_t which_led; 
    FacSwitch switch_state; 
    pb_size_t led_state_count;
    FacLedColor led_state[8]; 
    FacErrorCode result; 
} FacLedControl;

typedef struct _FacMotoControl { 
    FacMotoControlType type; 
    pb_size_t which_value_item;
    union {
        FacSwitch switch_state;
        FacMotoParam param;
        char file_name[128];
        FacMotoCali switch_cali;
        FacSwitch motor_testing;
        FacSwitch damping_switch;
        uint32_t motor_cali_result;
        ServoMotorParam servoparam;
    } value_item; 
    FacErrorCode result; 
} FacMotoControl;

typedef struct _FacUploadNineAlex { 
    pb_size_t data_count;
    NineAlexData data[15]; 
    FacErrorCode result; 
} FacUploadNineAlex;

typedef struct _FacWifiDemand { 
    float wifi_speed; 
    uint32_t connect_command; 
    uint32_t connect_result; 
    char ota_data[50]; 
    bool has_wifi_info;
    FacWifiInfo wifi_info; 
    uint32_t ota_result; 
    FacErrorCode result; 
} FacWifiDemand;

typedef struct _PresurceSensorData { 
    uint32_t timestamp; 
    uint32_t temperature; 
    bool has_brush_head;
    PresurceSensorItem brush_head; 
    bool has_mode_button;
    PresurceSensorItem mode_button; 
    bool has_power_button;
    PresurceSensorItem power_button; 
} PresurceSensorData;

typedef struct _FacButtonState { 
    pb_size_t button_state_count;
    FacButtonItem button_state[8]; 
    FacErrorCode result; 
} FacButtonState;

typedef struct _FacCollectParam { 
    pb_size_t param_count;
    FacDataCollectItem param[8]; 
    FacErrorCode result; 
} FacCollectParam;

typedef struct _FacDevInfo { 
    pb_size_t dev_info_count;
    FacDevInfoValue dev_info[5]; 
    FacErrorCode result; 
} FacDevInfo;

typedef struct _FacUploadPresSensor { 
    pb_size_t sensor_data_count;
    PresurceSensorData sensor_data[15]; 
    FacErrorCode result; 
} FacUploadPresSensor;

typedef struct _FactoryDataPackage { 
    FactroyCmd cmd_id; 
    pb_size_t which_command_data;
    union {
        FacGetDevBaseInfo get_dev_base_info;
        FacDevState set_dev_state;
        FacDevState get_dev_state;
        FacGetPeriphState get_periph_state;
        FacDevInfo get_dev_info;
        FacDevInfo set_dev_info;
        FacCollectParam set_collect_param;
        FacCollectParam get_collect_param;
        FacUploadPresSensor press_sensor;
        FacUploadNineAlex upload_nine_alex;
        FacButtonState get_button_state;
        FacButtonState upload_button_state;
        FacMotorCalibResult upload_motorcali_data;
        FacPreSensorCalibResult set_fsensor_calib;
        FacPreSensorCalibResult get_fsensor_calib;
        FacImuCalibResult set_imu_calib;
        FacImuCalibResult get_imu_calib;
        FacLedControl led_control;
        FacLcdControl lcd_control;
        FacMotoControl moto_control;
        FacBrushControl brush_control;
        FacSetTime set_time;
        FacCameraControl camera_control;
        FacAgeingTest ageing;
        FacSetBrushRecord set_brush_record;
        FacWifiDemand wifi_demand;
        FacInternetOta internet_ota;
    } command_data; 
} FactoryDataPackage;


/* Helper constants for enums */
#define _FacErrorCode_MIN FacErrorCode_NO_ERROR
#define _FacErrorCode_MAX FacErrorCode_GENERALLY
#define _FacErrorCode_ARRAYSIZE ((FacErrorCode)(FacErrorCode_GENERALLY+1))

#define _FactroyCmd_MIN FactroyCmd_FIRST_COMMAND_NO_USE
#define _FactroyCmd_MAX FactroyCmd_INTERNET_OTA
#define _FactroyCmd_ARRAYSIZE ((FactroyCmd)(FactroyCmd_INTERNET_OTA+1))

#define _FacProtoId_MIN FacProtoId_PROTOCOL_NONE
#define _FacProtoId_MAX FacProtoId_V1000
#define _FacProtoId_ARRAYSIZE ((FacProtoId)(FacProtoId_V1000+1))

#define _DevStateType_MIN DevStateType_REBOOT
#define _DevStateType_MAX DevStateType_SHIP
#define _DevStateType_ARRAYSIZE ((DevStateType)(DevStateType_SHIP+1))

#define _FacSwitch_MIN FacSwitch_CLOSE
#define _FacSwitch_MAX FacSwitch_START
#define _FacSwitch_ARRAYSIZE ((FacSwitch)(FacSwitch_START+1))

#define _FacDevInfoType_MIN FacDevInfoType_WIFI_INFO
#define _FacDevInfoType_MAX FacDevInfoType_IF_QUALIFIED
#define _FacDevInfoType_ARRAYSIZE ((FacDevInfoType)(FacDevInfoType_IF_QUALIFIED+1))

#define _FacChargeStateType_MIN FacChargeStateType_ERROR
#define _FacChargeStateType_MAX FacChargeStateType_NO_BATT
#define _FacChargeStateType_ARRAYSIZE ((FacChargeStateType)(FacChargeStateType_NO_BATT+1))

#define _FacAgeingTestType_MIN FacAgeingTestType_AGEING_1
#define _FacAgeingTestType_MAX FacAgeingTestType_AGEING_PRODUCTION_1
#define _FacAgeingTestType_ARRAYSIZE ((FacAgeingTestType)(FacAgeingTestType_AGEING_PRODUCTION_1+1))

#define _FacLcdControlType_MIN FacLcdControlType_color
#define _FacLcdControlType_MAX FacLcdControlType_reg
#define _FacLcdControlType_ARRAYSIZE ((FacLcdControlType)(FacLcdControlType_reg+1))

#define _FacMotoControlType_MIN FacMotoControlType_motor_state
#define _FacMotoControlType_MAX FacMotoControlType_servo_param
#define _FacMotoControlType_ARRAYSIZE ((FacMotoControlType)(FacMotoControlType_servo_param+1))

#define _FacMotoCali_MIN FacMotoCali_HALL_CALIBRATION
#define _FacMotoCali_MAX FacMotoCali_MOTOR_CALI_STOP
#define _FacMotoCali_ARRAYSIZE ((FacMotoCali)(FacMotoCali_MOTOR_CALI_STOP+1))

#define _FacMotorUploadType_MIN FacMotorUploadType_HALL_CALIBRATION_DATA
#define _FacMotorUploadType_MAX FacMotorUploadType_MOTOR_LOG
#define _FacMotorUploadType_ARRAYSIZE ((FacMotorUploadType)(FacMotorUploadType_MOTOR_LOG+1))

#define _FacCameraControlType_MIN FacCameraControlType_camera_state
#define _FacCameraControlType_MAX FacCameraControlType_camera_get_picture
#define _FacCameraControlType_ARRAYSIZE ((FacCameraControlType)(FacCameraControlType_camera_get_picture+1))

#define _LedPosition_MIN LedPosition_led_left_up
#define _LedPosition_MAX LedPosition_led_right_down
#define _LedPosition_ARRAYSIZE ((LedPosition)(LedPosition_led_right_down+1))

#define _DataCollectType_MIN DataCollectType_BATTERY
#define _DataCollectType_MAX DataCollectType_NINE_AXLE
#define _DataCollectType_ARRAYSIZE ((DataCollectType)(DataCollectType_NINE_AXLE+1))

#define _FacBrushControlType_MIN FacBrushControlType_BRUSH_START
#define _FacBrushControlType_MAX FacBrushControlType_CHANGE_MODE
#define _FacBrushControlType_ARRAYSIZE ((FacBrushControlType)(FacBrushControlType_CHANGE_MODE+1))

#define _FacButtonType_MIN FacButtonType_POWER_BUTTON
#define _FacButtonType_MAX FacButtonType_PRESS_MECHANICAL
#define _FacButtonType_ARRAYSIZE ((FacButtonType)(FacButtonType_PRESS_MECHANICAL+1))

#define _ButtonState_MIN ButtonState_NULL
#define _ButtonState_MAX ButtonState_HELD
#define _ButtonState_ARRAYSIZE ((ButtonState)(ButtonState_HELD+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define FactoryDataPackage_init_default          {_FactroyCmd_MIN, 0, {FacGetDevBaseInfo_init_default}}
#define FacGetDevBaseInfo_init_default           {"", 0, _FacProtoId_MIN, "", "", "", "", "", {0, {0}}, {0, {0}}, 0, 0, "", _FacErrorCode_MIN}
#define FacDevState_init_default                 {_DevStateType_MIN, _FacSwitch_MIN, _FacErrorCode_MIN}
#define FacBatteryInfo_init_default              {_FacChargeStateType_MIN, 0, 0}
#define FacWifiInfo_init_default                 {"", "", {0, {0}}, 0}
#define FacDevInfoValue_init_default             {_FacDevInfoType_MIN, 0, {FacWifiInfo_init_default}}
#define FacDevInfo_init_default                  {0, {FacDevInfoValue_init_default, FacDevInfoValue_init_default, FacDevInfoValue_init_default, FacDevInfoValue_init_default, FacDevInfoValue_init_default}, _FacErrorCode_MIN}
#define FacGetPeriphState_init_default           {0, 0, 0, 0, 0, _FacErrorCode_MIN}
#define FacAgeingTest_init_default               {_FacAgeingTestType_MIN, _FacSwitch_MIN, 0, 0, 0, 0, _FacErrorCode_MIN}
#define FacRegisterConfig_init_default           {0, 0}
#define FacLcdControl_init_default               {_FacLcdControlType_MIN, 0, {0}, _FacErrorCode_MIN}
#define FacMotoParam_init_default                {0, 0, 0}
#define ServoMotorParam_init_default             {0, 0, 0, 0}
#define FacMotoControl_init_default              {_FacMotoControlType_MIN, 0, {_FacSwitch_MIN}, _FacErrorCode_MIN}
#define FacMotorCalibResult_init_default         {_FacMotorUploadType_MIN, 0, {0}, _FacErrorCode_MIN}
#define FacCameraControl_init_default            {_FacCameraControlType_MIN, 0, {_FacSwitch_MIN}, _FacErrorCode_MIN}
#define FacLedColor_init_default                 {_LedPosition_MIN, 0, 0, 0}
#define FacLedControl_init_default               {0, _FacSwitch_MIN, 0, {FacLedColor_init_default, FacLedColor_init_default, FacLedColor_init_default, FacLedColor_init_default, FacLedColor_init_default, FacLedColor_init_default, FacLedColor_init_default, FacLedColor_init_default}, _FacErrorCode_MIN}
#define FacBrushControl_init_default             {_FacBrushControlType_MIN, 0, {_FacSwitch_MIN}, _FacErrorCode_MIN}
#define DataCollectParam_init_default            {_FacSwitch_MIN, 0, 0, 0}
#define FacDataCollectItem_init_default          {_DataCollectType_MIN, 0, {DataCollectParam_init_default}}
#define FacCollectParam_init_default             {0, {FacDataCollectItem_init_default, FacDataCollectItem_init_default, FacDataCollectItem_init_default, FacDataCollectItem_init_default, FacDataCollectItem_init_default, FacDataCollectItem_init_default, FacDataCollectItem_init_default, FacDataCollectItem_init_default}, _FacErrorCode_MIN}
#define DataButtonParam_init_default             {_FacSwitch_MIN, _ButtonState_MIN}
#define FacButtonItem_init_default               {_FacButtonType_MIN, 0, {DataButtonParam_init_default}}
#define FacButtonState_init_default              {0, {FacButtonItem_init_default, FacButtonItem_init_default, FacButtonItem_init_default, FacButtonItem_init_default, FacButtonItem_init_default, FacButtonItem_init_default, FacButtonItem_init_default, FacButtonItem_init_default}, _FacErrorCode_MIN}
#define FacWifiDemand_init_default               {0, 0, 0, "", false, FacWifiInfo_init_default, 0, _FacErrorCode_MIN}
#define NineAlexData_init_default                {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define FacUploadNineAlex_init_default           {0, {NineAlexData_init_default, NineAlexData_init_default, NineAlexData_init_default, NineAlexData_init_default, NineAlexData_init_default, NineAlexData_init_default, NineAlexData_init_default, NineAlexData_init_default, NineAlexData_init_default, NineAlexData_init_default, NineAlexData_init_default, NineAlexData_init_default, NineAlexData_init_default, NineAlexData_init_default, NineAlexData_init_default}, _FacErrorCode_MIN}
#define PresurceSensorItem_init_default          {0, 0}
#define PresurceSensorData_init_default          {0, 0, false, PresurceSensorItem_init_default, false, PresurceSensorItem_init_default, false, PresurceSensorItem_init_default}
#define FacUploadPresSensor_init_default         {0, {PresurceSensorData_init_default, PresurceSensorData_init_default, PresurceSensorData_init_default, PresurceSensorData_init_default, PresurceSensorData_init_default, PresurceSensorData_init_default, PresurceSensorData_init_default, PresurceSensorData_init_default, PresurceSensorData_init_default, PresurceSensorData_init_default, PresurceSensorData_init_default, PresurceSensorData_init_default, PresurceSensorData_init_default, PresurceSensorData_init_default, PresurceSensorData_init_default}, _FacErrorCode_MIN}
#define FacPreSensorCalibResult_init_default     {0, 0, 0, 0, _FacErrorCode_MIN}
#define AccCaliData_init_default                 {0, 0, 0, 0, 0, 0, 0, 0, 0}
#define FacImuCalibResult_init_default           {0, 0, 0, 0, 0, 0, false, AccCaliData_init_default, _FacErrorCode_MIN}
#define FacSetTime_init_default                  {0, 0}
#define FacSetBrushRecord_init_default           {0, 0, {0, {0}}, {0, {0}}, {0, {0}}}
#define FacOtaFileInfo_init_default              {0, 0, 0, "", ""}
#define FacInternetOta_init_default              {0, {FacOtaFileInfo_init_default, FacOtaFileInfo_init_default}, _FacErrorCode_MIN}
#define FactoryDataPackage_init_zero             {_FactroyCmd_MIN, 0, {FacGetDevBaseInfo_init_zero}}
#define FacGetDevBaseInfo_init_zero              {"", 0, _FacProtoId_MIN, "", "", "", "", "", {0, {0}}, {0, {0}}, 0, 0, "", _FacErrorCode_MIN}
#define FacDevState_init_zero                    {_DevStateType_MIN, _FacSwitch_MIN, _FacErrorCode_MIN}
#define FacBatteryInfo_init_zero                 {_FacChargeStateType_MIN, 0, 0}
#define FacWifiInfo_init_zero                    {"", "", {0, {0}}, 0}
#define FacDevInfoValue_init_zero                {_FacDevInfoType_MIN, 0, {FacWifiInfo_init_zero}}
#define FacDevInfo_init_zero                     {0, {FacDevInfoValue_init_zero, FacDevInfoValue_init_zero, FacDevInfoValue_init_zero, FacDevInfoValue_init_zero, FacDevInfoValue_init_zero}, _FacErrorCode_MIN}
#define FacGetPeriphState_init_zero              {0, 0, 0, 0, 0, _FacErrorCode_MIN}
#define FacAgeingTest_init_zero                  {_FacAgeingTestType_MIN, _FacSwitch_MIN, 0, 0, 0, 0, _FacErrorCode_MIN}
#define FacRegisterConfig_init_zero              {0, 0}
#define FacLcdControl_init_zero                  {_FacLcdControlType_MIN, 0, {0}, _FacErrorCode_MIN}
#define FacMotoParam_init_zero                   {0, 0, 0}
#define ServoMotorParam_init_zero                {0, 0, 0, 0}
#define FacMotoControl_init_zero                 {_FacMotoControlType_MIN, 0, {_FacSwitch_MIN}, _FacErrorCode_MIN}
#define FacMotorCalibResult_init_zero            {_FacMotorUploadType_MIN, 0, {0}, _FacErrorCode_MIN}
#define FacCameraControl_init_zero               {_FacCameraControlType_MIN, 0, {_FacSwitch_MIN}, _FacErrorCode_MIN}
#define FacLedColor_init_zero                    {_LedPosition_MIN, 0, 0, 0}
#define FacLedControl_init_zero                  {0, _FacSwitch_MIN, 0, {FacLedColor_init_zero, FacLedColor_init_zero, FacLedColor_init_zero, FacLedColor_init_zero, FacLedColor_init_zero, FacLedColor_init_zero, FacLedColor_init_zero, FacLedColor_init_zero}, _FacErrorCode_MIN}
#define FacBrushControl_init_zero                {_FacBrushControlType_MIN, 0, {_FacSwitch_MIN}, _FacErrorCode_MIN}
#define DataCollectParam_init_zero               {_FacSwitch_MIN, 0, 0, 0}
#define FacDataCollectItem_init_zero             {_DataCollectType_MIN, 0, {DataCollectParam_init_zero}}
#define FacCollectParam_init_zero                {0, {FacDataCollectItem_init_zero, FacDataCollectItem_init_zero, FacDataCollectItem_init_zero, FacDataCollectItem_init_zero, FacDataCollectItem_init_zero, FacDataCollectItem_init_zero, FacDataCollectItem_init_zero, FacDataCollectItem_init_zero}, _FacErrorCode_MIN}
#define DataButtonParam_init_zero                {_FacSwitch_MIN, _ButtonState_MIN}
#define FacButtonItem_init_zero                  {_FacButtonType_MIN, 0, {DataButtonParam_init_zero}}
#define FacButtonState_init_zero                 {0, {FacButtonItem_init_zero, FacButtonItem_init_zero, FacButtonItem_init_zero, FacButtonItem_init_zero, FacButtonItem_init_zero, FacButtonItem_init_zero, FacButtonItem_init_zero, FacButtonItem_init_zero}, _FacErrorCode_MIN}
#define FacWifiDemand_init_zero                  {0, 0, 0, "", false, FacWifiInfo_init_zero, 0, _FacErrorCode_MIN}
#define NineAlexData_init_zero                   {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define FacUploadNineAlex_init_zero              {0, {NineAlexData_init_zero, NineAlexData_init_zero, NineAlexData_init_zero, NineAlexData_init_zero, NineAlexData_init_zero, NineAlexData_init_zero, NineAlexData_init_zero, NineAlexData_init_zero, NineAlexData_init_zero, NineAlexData_init_zero, NineAlexData_init_zero, NineAlexData_init_zero, NineAlexData_init_zero, NineAlexData_init_zero, NineAlexData_init_zero}, _FacErrorCode_MIN}
#define PresurceSensorItem_init_zero             {0, 0}
#define PresurceSensorData_init_zero             {0, 0, false, PresurceSensorItem_init_zero, false, PresurceSensorItem_init_zero, false, PresurceSensorItem_init_zero}
#define FacUploadPresSensor_init_zero            {0, {PresurceSensorData_init_zero, PresurceSensorData_init_zero, PresurceSensorData_init_zero, PresurceSensorData_init_zero, PresurceSensorData_init_zero, PresurceSensorData_init_zero, PresurceSensorData_init_zero, PresurceSensorData_init_zero, PresurceSensorData_init_zero, PresurceSensorData_init_zero, PresurceSensorData_init_zero, PresurceSensorData_init_zero, PresurceSensorData_init_zero, PresurceSensorData_init_zero, PresurceSensorData_init_zero}, _FacErrorCode_MIN}
#define FacPreSensorCalibResult_init_zero        {0, 0, 0, 0, _FacErrorCode_MIN}
#define AccCaliData_init_zero                    {0, 0, 0, 0, 0, 0, 0, 0, 0}
#define FacImuCalibResult_init_zero              {0, 0, 0, 0, 0, 0, false, AccCaliData_init_zero, _FacErrorCode_MIN}
#define FacSetTime_init_zero                     {0, 0}
#define FacSetBrushRecord_init_zero              {0, 0, {0, {0}}, {0, {0}}, {0, {0}}}
#define FacOtaFileInfo_init_zero                 {0, 0, 0, "", ""}
#define FacInternetOta_init_zero                 {0, {FacOtaFileInfo_init_zero, FacOtaFileInfo_init_zero}, _FacErrorCode_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define AccCaliData_kx_tag                       1
#define AccCaliData_ky_tag                       2
#define AccCaliData_kz_tag                       3
#define AccCaliData_syx_tag                      4
#define AccCaliData_szx_tag                      5
#define AccCaliData_szy_tag                      6
#define AccCaliData_bx_tag                       7
#define AccCaliData_by_tag                       8
#define AccCaliData_bz_tag                       9
#define DataButtonParam_state_tag                1
#define DataButtonParam_button_state_now_tag     2
#define DataCollectParam_state_tag               1
#define DataCollectParam_sampling_count_tag      2
#define DataCollectParam_sampling_rate_tag       3
#define DataCollectParam_upload_rate_tag         4
#define FacAgeingTest_type_tag                   1
#define FacAgeingTest_switch_state_tag           2
#define FacAgeingTest_brush_mode_tag             3
#define FacAgeingTest_work_time_tag              4
#define FacAgeingTest_stop_time_tag              5
#define FacAgeingTest_cycle_count_tag            6
#define FacAgeingTest_result_tag                 100
#define FacBatteryInfo_charge_state_tag          1
#define FacBatteryInfo_voltage_tag               2
#define FacBatteryInfo_percent_tag               3
#define FacBrushControl_type_tag                 1
#define FacBrushControl_brush_start_tag          2
#define FacBrushControl_change_mode_tag          3
#define FacBrushControl_result_tag               100
#define FacCameraControl_type_tag                1
#define FacCameraControl_camera_switch_tag       2
#define FacCameraControl_light_switch_tag        3
#define FacCameraControl_exposure_time_tag       4
#define FacCameraControl_display_on_screen_tag   5
#define FacCameraControl_camera_support_tag      6
#define FacCameraControl_get_picture_tag         7
#define FacCameraControl_result_tag              100
#define FacDevState_dev_state_type_tag           1
#define FacDevState_state_tag                    2
#define FacDevState_result_tag                   100
#define FacGetDevBaseInfo_product_name_tag       1
#define FacGetDevBaseInfo_pb_phone_ver_tag       2
#define FacGetDevBaseInfo_pb_factory_ver_tag     3
#define FacGetDevBaseInfo_hw_version_tag         4
#define FacGetDevBaseInfo_soft_version_tag       5
#define FacGetDevBaseInfo_res_version_tag        6
#define FacGetDevBaseInfo_algo_version_tag       7
#define FacGetDevBaseInfo_presure_version_tag    8
#define FacGetDevBaseInfo_ble_mac_tag            9
#define FacGetDevBaseInfo_wifi_mac_tag           10
#define FacGetDevBaseInfo_imu_id_tag             11
#define FacGetDevBaseInfo_ageing_state_tag       12
#define FacGetDevBaseInfo_motor_version_tag      13
#define FacGetDevBaseInfo_result_tag             100
#define FacGetPeriphState_imu_state_tag          1
#define FacGetPeriphState_flash_state_tag        2
#define FacGetPeriphState_magnet_state_tag       3
#define FacGetPeriphState_press_state_tag        4
#define FacGetPeriphState_audio_state_tag        5
#define FacGetPeriphState_result_tag             100
#define FacLedColor_index_tag                    1
#define FacLedColor_R_tag                        2
#define FacLedColor_G_tag                        3
#define FacLedColor_B_tag                        4
#define FacMotoParam_freq_tag                    1
#define FacMotoParam_gain_or_duty_tag            2
#define FacMotoParam_volume_tag                  3
#define FacMotorCalibResult_type_tag             1
#define FacMotorCalibResult_hall_calibration_data_tag 2
#define FacMotorCalibResult_zero_calibration_data_tag 3
#define FacMotorCalibResult_motor_log_tag        4
#define FacMotorCalibResult_result_tag           100
#define FacOtaFileInfo_file_size_tag             1
#define FacOtaFileInfo_version_code_tag          2
#define FacOtaFileInfo_version_type_tag          3
#define FacOtaFileInfo_url_tag                   4
#define FacOtaFileInfo_md5_tag                   5
#define FacPreSensorCalibResult_brush_head_adc_tag 1
#define FacPreSensorCalibResult_mode_button_adc_tag 2
#define FacPreSensorCalibResult_power_button_adc_tag 3
#define FacPreSensorCalibResult_temperature_tag  4
#define FacPreSensorCalibResult_result_tag       100
#define FacRegisterConfig_addr_tag               1
#define FacRegisterConfig_value_tag              2
#define FacSetBrushRecord_timestamp_tag          1
#define FacSetBrushRecord_plaque_tag             2
#define FacSetBrushRecord_work_time_tag          3
#define FacSetBrushRecord_pressure_time_tag      4
#define FacSetBrushRecord_horizon_brush_tag      5
#define FacSetTime_timestamp_tag                 1
#define FacSetTime_timezone_tag                  2
#define FacWifiInfo_wifi_name_tag                1
#define FacWifiInfo_wifi_password_tag            2
#define FacWifiInfo_ip_address_tag               3
#define FacWifiInfo_port_tag                     4
#define NineAlexData_timestamp_tag               1
#define NineAlexData_acc_x_tag                   2
#define NineAlexData_acc_y_tag                   3
#define NineAlexData_acc_z_tag                   4
#define NineAlexData_gyro_x_tag                  5
#define NineAlexData_gyro_y_tag                  6
#define NineAlexData_gyro_z_tag                  7
#define NineAlexData_magnet_x_tag                8
#define NineAlexData_magnet_y_tag                9
#define NineAlexData_magnet_z_tag                10
#define PresurceSensorItem_adc_tag               1
#define PresurceSensorItem_value_tag             2
#define ServoMotorParam_vibrate_angle_tag        1
#define ServoMotorParam_sweeping_angle_tag       2
#define ServoMotorParam_vibrate_freq_tag         3
#define ServoMotorParam_sweeping_freq_tag        4
#define FacButtonItem_type_tag                   1
#define FacButtonItem_power_button_tag           2
#define FacButtonItem_mode_button_tag            3
#define FacButtonItem_press_mechanical_tag       4
#define FacDataCollectItem_type_tag              1
#define FacDataCollectItem_bat_vol_tag           2
#define FacDataCollectItem_pressure_sensor_tag   3
#define FacDataCollectItem_nine_axle_tag         4
#define FacDevInfoValue_info_item_tag            1
#define FacDevInfoValue_wifi_info_tag            2
#define FacDevInfoValue_tail_sn_tag              3
#define FacDevInfoValue_board_sn_tag             4
#define FacDevInfoValue_brush_mode_tag           5
#define FacDevInfoValue_battery_tag              6
#define FacDevInfoValue_if_qualified_tag         7
#define FacImuCalibResult_gyro_x_tag             1
#define FacImuCalibResult_gyro_y_tag             2
#define FacImuCalibResult_gyro_z_tag             3
#define FacImuCalibResult_acc_x_tag              4
#define FacImuCalibResult_acc_y_tag              5
#define FacImuCalibResult_acc_z_tag              6
#define FacImuCalibResult_new_cali_tag           7
#define FacImuCalibResult_result_tag             100
#define FacInternetOta_file_info_tag             1
#define FacInternetOta_result_tag                100
#define FacLcdControl_type_tag                   1
#define FacLcdControl_color_tag                  2
#define FacLcdControl_config_tag                 3
#define FacLcdControl_result_tag                 100
#define FacLedControl_which_led_tag              1
#define FacLedControl_switch_state_tag           2
#define FacLedControl_led_state_tag              3
#define FacLedControl_result_tag                 100
#define FacMotoControl_type_tag                  1
#define FacMotoControl_switch_state_tag          2
#define FacMotoControl_param_tag                 3
#define FacMotoControl_file_name_tag             4
#define FacMotoControl_switch_cali_tag           5
#define FacMotoControl_motor_testing_tag         6
#define FacMotoControl_damping_switch_tag        7
#define FacMotoControl_motor_cali_result_tag     8
#define FacMotoControl_servoparam_tag            9
#define FacMotoControl_result_tag                100
#define FacUploadNineAlex_data_tag               2
#define FacUploadNineAlex_result_tag             100
#define FacWifiDemand_wifi_speed_tag             1
#define FacWifiDemand_connect_command_tag        2
#define FacWifiDemand_connect_result_tag         3
#define FacWifiDemand_ota_data_tag               4
#define FacWifiDemand_wifi_info_tag              5
#define FacWifiDemand_ota_result_tag             6
#define FacWifiDemand_result_tag                 100
#define PresurceSensorData_timestamp_tag         1
#define PresurceSensorData_temperature_tag       2
#define PresurceSensorData_brush_head_tag        3
#define PresurceSensorData_mode_button_tag       4
#define PresurceSensorData_power_button_tag      5
#define FacButtonState_button_state_tag          2
#define FacButtonState_result_tag                100
#define FacCollectParam_param_tag                2
#define FacCollectParam_result_tag               100
#define FacDevInfo_dev_info_tag                  1
#define FacDevInfo_result_tag                    100
#define FacUploadPresSensor_sensor_data_tag      2
#define FacUploadPresSensor_result_tag           100
#define FactoryDataPackage_cmd_id_tag            1
#define FactoryDataPackage_get_dev_base_info_tag 2
#define FactoryDataPackage_set_dev_state_tag     3
#define FactoryDataPackage_get_dev_state_tag     4
#define FactoryDataPackage_get_periph_state_tag  5
#define FactoryDataPackage_get_dev_info_tag      6
#define FactoryDataPackage_set_dev_info_tag      7
#define FactoryDataPackage_set_collect_param_tag 16
#define FactoryDataPackage_get_collect_param_tag 17
#define FactoryDataPackage_press_sensor_tag      19
#define FactoryDataPackage_upload_nine_alex_tag  20
#define FactoryDataPackage_get_button_state_tag  21
#define FactoryDataPackage_upload_button_state_tag 22
#define FactoryDataPackage_upload_motorcali_data_tag 23
#define FactoryDataPackage_set_fsensor_calib_tag 32
#define FactoryDataPackage_get_fsensor_calib_tag 33
#define FactoryDataPackage_set_imu_calib_tag     34
#define FactoryDataPackage_get_imu_calib_tag     35
#define FactoryDataPackage_led_control_tag       36
#define FactoryDataPackage_lcd_control_tag       37
#define FactoryDataPackage_moto_control_tag      38
#define FactoryDataPackage_brush_control_tag     39
#define FactoryDataPackage_set_time_tag          40
#define FactoryDataPackage_camera_control_tag    41
#define FactoryDataPackage_ageing_tag            50
#define FactoryDataPackage_set_brush_record_tag  51
#define FactoryDataPackage_wifi_demand_tag       52
#define FactoryDataPackage_internet_ota_tag      64

/* Struct field encoding specification for nanopb */
#define FactoryDataPackage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    cmd_id,            1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command_data,get_dev_base_info,command_data.get_dev_base_info),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command_data,set_dev_state,command_data.set_dev_state),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command_data,get_dev_state,command_data.get_dev_state),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command_data,get_periph_state,command_data.get_periph_state),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command_data,get_dev_info,command_data.get_dev_info),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command_data,set_dev_info,command_data.set_dev_info),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command_data,set_collect_param,command_data.set_collect_param),  16) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command_data,get_collect_param,command_data.get_collect_param),  17) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command_data,press_sensor,command_data.press_sensor),  19) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command_data,upload_nine_alex,command_data.upload_nine_alex),  20) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command_data,get_button_state,command_data.get_button_state),  21) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command_data,upload_button_state,command_data.upload_button_state),  22) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command_data,upload_motorcali_data,command_data.upload_motorcali_data),  23) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command_data,set_fsensor_calib,command_data.set_fsensor_calib),  32) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command_data,get_fsensor_calib,command_data.get_fsensor_calib),  33) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command_data,set_imu_calib,command_data.set_imu_calib),  34) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command_data,get_imu_calib,command_data.get_imu_calib),  35) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command_data,led_control,command_data.led_control),  36) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command_data,lcd_control,command_data.lcd_control),  37) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command_data,moto_control,command_data.moto_control),  38) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command_data,brush_control,command_data.brush_control),  39) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command_data,set_time,command_data.set_time),  40) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command_data,camera_control,command_data.camera_control),  41) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command_data,ageing,command_data.ageing),  50) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command_data,set_brush_record,command_data.set_brush_record),  51) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command_data,wifi_demand,command_data.wifi_demand),  52) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command_data,internet_ota,command_data.internet_ota),  64)
#define FactoryDataPackage_CALLBACK NULL
#define FactoryDataPackage_DEFAULT NULL
#define FactoryDataPackage_command_data_get_dev_base_info_MSGTYPE FacGetDevBaseInfo
#define FactoryDataPackage_command_data_set_dev_state_MSGTYPE FacDevState
#define FactoryDataPackage_command_data_get_dev_state_MSGTYPE FacDevState
#define FactoryDataPackage_command_data_get_periph_state_MSGTYPE FacGetPeriphState
#define FactoryDataPackage_command_data_get_dev_info_MSGTYPE FacDevInfo
#define FactoryDataPackage_command_data_set_dev_info_MSGTYPE FacDevInfo
#define FactoryDataPackage_command_data_set_collect_param_MSGTYPE FacCollectParam
#define FactoryDataPackage_command_data_get_collect_param_MSGTYPE FacCollectParam
#define FactoryDataPackage_command_data_press_sensor_MSGTYPE FacUploadPresSensor
#define FactoryDataPackage_command_data_upload_nine_alex_MSGTYPE FacUploadNineAlex
#define FactoryDataPackage_command_data_get_button_state_MSGTYPE FacButtonState
#define FactoryDataPackage_command_data_upload_button_state_MSGTYPE FacButtonState
#define FactoryDataPackage_command_data_upload_motorcali_data_MSGTYPE FacMotorCalibResult
#define FactoryDataPackage_command_data_set_fsensor_calib_MSGTYPE FacPreSensorCalibResult
#define FactoryDataPackage_command_data_get_fsensor_calib_MSGTYPE FacPreSensorCalibResult
#define FactoryDataPackage_command_data_set_imu_calib_MSGTYPE FacImuCalibResult
#define FactoryDataPackage_command_data_get_imu_calib_MSGTYPE FacImuCalibResult
#define FactoryDataPackage_command_data_led_control_MSGTYPE FacLedControl
#define FactoryDataPackage_command_data_lcd_control_MSGTYPE FacLcdControl
#define FactoryDataPackage_command_data_moto_control_MSGTYPE FacMotoControl
#define FactoryDataPackage_command_data_brush_control_MSGTYPE FacBrushControl
#define FactoryDataPackage_command_data_set_time_MSGTYPE FacSetTime
#define FactoryDataPackage_command_data_camera_control_MSGTYPE FacCameraControl
#define FactoryDataPackage_command_data_ageing_MSGTYPE FacAgeingTest
#define FactoryDataPackage_command_data_set_brush_record_MSGTYPE FacSetBrushRecord
#define FactoryDataPackage_command_data_wifi_demand_MSGTYPE FacWifiDemand
#define FactoryDataPackage_command_data_internet_ota_MSGTYPE FacInternetOta

#define FacGetDevBaseInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   product_name,      1) \
X(a, STATIC,   SINGULAR, UINT32,   pb_phone_ver,      2) \
X(a, STATIC,   SINGULAR, UENUM,    pb_factory_ver,    3) \
X(a, STATIC,   SINGULAR, STRING,   hw_version,        4) \
X(a, STATIC,   SINGULAR, STRING,   soft_version,      5) \
X(a, STATIC,   SINGULAR, STRING,   res_version,       6) \
X(a, STATIC,   SINGULAR, STRING,   algo_version,      7) \
X(a, STATIC,   SINGULAR, STRING,   presure_version,   8) \
X(a, STATIC,   SINGULAR, BYTES,    ble_mac,           9) \
X(a, STATIC,   SINGULAR, BYTES,    wifi_mac,         10) \
X(a, STATIC,   SINGULAR, UINT32,   imu_id,           11) \
X(a, STATIC,   SINGULAR, BOOL,     ageing_state,     12) \
X(a, STATIC,   SINGULAR, STRING,   motor_version,    13) \
X(a, STATIC,   SINGULAR, UENUM,    result,          100)
#define FacGetDevBaseInfo_CALLBACK NULL
#define FacGetDevBaseInfo_DEFAULT NULL

#define FacDevState_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    dev_state_type,    1) \
X(a, STATIC,   SINGULAR, UENUM,    state,             2) \
X(a, STATIC,   SINGULAR, UENUM,    result,          100)
#define FacDevState_CALLBACK NULL
#define FacDevState_DEFAULT NULL

#define FacBatteryInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    charge_state,      1) \
X(a, STATIC,   SINGULAR, UINT32,   voltage,           2) \
X(a, STATIC,   SINGULAR, UINT32,   percent,           3)
#define FacBatteryInfo_CALLBACK NULL
#define FacBatteryInfo_DEFAULT NULL

#define FacWifiInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   wifi_name,         1) \
X(a, STATIC,   SINGULAR, STRING,   wifi_password,     2) \
X(a, STATIC,   SINGULAR, BYTES,    ip_address,        3) \
X(a, STATIC,   SINGULAR, UINT32,   port,              4)
#define FacWifiInfo_CALLBACK NULL
#define FacWifiInfo_DEFAULT NULL

#define FacDevInfoValue_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    info_item,         1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (value_item,wifi_info,value_item.wifi_info),   2) \
X(a, STATIC,   ONEOF,    STRING,   (value_item,tail_sn,value_item.tail_sn),   3) \
X(a, STATIC,   ONEOF,    STRING,   (value_item,board_sn,value_item.board_sn),   4) \
X(a, STATIC,   ONEOF,    UINT32,   (value_item,brush_mode,value_item.brush_mode),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (value_item,battery,value_item.battery),   6) \
X(a, STATIC,   ONEOF,    UENUM,    (value_item,if_qualified,value_item.if_qualified),   7)
#define FacDevInfoValue_CALLBACK NULL
#define FacDevInfoValue_DEFAULT NULL
#define FacDevInfoValue_value_item_wifi_info_MSGTYPE FacWifiInfo
#define FacDevInfoValue_value_item_battery_MSGTYPE FacBatteryInfo

#define FacDevInfo_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  dev_info,          1) \
X(a, STATIC,   SINGULAR, UENUM,    result,          100)
#define FacDevInfo_CALLBACK NULL
#define FacDevInfo_DEFAULT NULL
#define FacDevInfo_dev_info_MSGTYPE FacDevInfoValue

#define FacGetPeriphState_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     imu_state,         1) \
X(a, STATIC,   SINGULAR, BOOL,     flash_state,       2) \
X(a, STATIC,   SINGULAR, BOOL,     magnet_state,      3) \
X(a, STATIC,   SINGULAR, BOOL,     press_state,       4) \
X(a, STATIC,   SINGULAR, BOOL,     audio_state,       5) \
X(a, STATIC,   SINGULAR, UENUM,    result,          100)
#define FacGetPeriphState_CALLBACK NULL
#define FacGetPeriphState_DEFAULT NULL

#define FacAgeingTest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   SINGULAR, UENUM,    switch_state,      2) \
X(a, STATIC,   SINGULAR, UINT32,   brush_mode,        3) \
X(a, STATIC,   SINGULAR, UINT32,   work_time,         4) \
X(a, STATIC,   SINGULAR, UINT32,   stop_time,         5) \
X(a, STATIC,   SINGULAR, UINT32,   cycle_count,       6) \
X(a, STATIC,   SINGULAR, UENUM,    result,          100)
#define FacAgeingTest_CALLBACK NULL
#define FacAgeingTest_DEFAULT NULL

#define FacRegisterConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   addr,              1) \
X(a, STATIC,   SINGULAR, UINT32,   value,             2)
#define FacRegisterConfig_CALLBACK NULL
#define FacRegisterConfig_DEFAULT NULL

#define FacLcdControl_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   ONEOF,    UINT32,   (value_item,color,value_item.color),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (value_item,config,value_item.config),   3) \
X(a, STATIC,   SINGULAR, UENUM,    result,          100)
#define FacLcdControl_CALLBACK NULL
#define FacLcdControl_DEFAULT NULL
#define FacLcdControl_value_item_config_MSGTYPE FacRegisterConfig

#define FacMotoParam_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   freq,              1) \
X(a, STATIC,   SINGULAR, FLOAT,    gain_or_duty,      2) \
X(a, STATIC,   SINGULAR, UINT32,   volume,            3)
#define FacMotoParam_CALLBACK NULL
#define FacMotoParam_DEFAULT NULL

#define ServoMotorParam_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    vibrate_angle,     1) \
X(a, STATIC,   SINGULAR, UINT32,   sweeping_angle,    2) \
X(a, STATIC,   SINGULAR, UINT32,   vibrate_freq,      3) \
X(a, STATIC,   SINGULAR, FLOAT,    sweeping_freq,     4)
#define ServoMotorParam_CALLBACK NULL
#define ServoMotorParam_DEFAULT NULL

#define FacMotoControl_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   ONEOF,    UENUM,    (value_item,switch_state,value_item.switch_state),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (value_item,param,value_item.param),   3) \
X(a, STATIC,   ONEOF,    STRING,   (value_item,file_name,value_item.file_name),   4) \
X(a, STATIC,   ONEOF,    UENUM,    (value_item,switch_cali,value_item.switch_cali),   5) \
X(a, STATIC,   ONEOF,    UENUM,    (value_item,motor_testing,value_item.motor_testing),   6) \
X(a, STATIC,   ONEOF,    UENUM,    (value_item,damping_switch,value_item.damping_switch),   7) \
X(a, STATIC,   ONEOF,    UINT32,   (value_item,motor_cali_result,value_item.motor_cali_result),   8) \
X(a, STATIC,   ONEOF,    MESSAGE,  (value_item,servoparam,value_item.servoparam),   9) \
X(a, STATIC,   SINGULAR, UENUM,    result,          100)
#define FacMotoControl_CALLBACK NULL
#define FacMotoControl_DEFAULT NULL
#define FacMotoControl_value_item_param_MSGTYPE FacMotoParam
#define FacMotoControl_value_item_servoparam_MSGTYPE ServoMotorParam

#define FacMotorCalibResult_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   ONEOF,    UINT32,   (value_item,hall_calibration_data,value_item.hall_calibration_data),   2) \
X(a, STATIC,   ONEOF,    UINT32,   (value_item,zero_calibration_data,value_item.zero_calibration_data),   3) \
X(a, STATIC,   ONEOF,    STRING,   (value_item,motor_log,value_item.motor_log),   4) \
X(a, STATIC,   SINGULAR, UENUM,    result,          100)
#define FacMotorCalibResult_CALLBACK NULL
#define FacMotorCalibResult_DEFAULT NULL

#define FacCameraControl_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   ONEOF,    UENUM,    (value_item,camera_switch,value_item.camera_switch),   2) \
X(a, STATIC,   ONEOF,    UENUM,    (value_item,light_switch,value_item.light_switch),   3) \
X(a, STATIC,   ONEOF,    UINT32,   (value_item,exposure_time,value_item.exposure_time),   4) \
X(a, STATIC,   ONEOF,    UENUM,    (value_item,display_on_screen,value_item.display_on_screen),   5) \
X(a, STATIC,   ONEOF,    UENUM,    (value_item,camera_support,value_item.camera_support),   6) \
X(a, STATIC,   ONEOF,    UENUM,    (value_item,get_picture,value_item.get_picture),   7) \
X(a, STATIC,   SINGULAR, UENUM,    result,          100)
#define FacCameraControl_CALLBACK NULL
#define FacCameraControl_DEFAULT NULL

#define FacLedColor_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    index,             1) \
X(a, STATIC,   SINGULAR, UINT32,   R,                 2) \
X(a, STATIC,   SINGULAR, UINT32,   G,                 3) \
X(a, STATIC,   SINGULAR, UINT32,   B,                 4)
#define FacLedColor_CALLBACK NULL
#define FacLedColor_DEFAULT NULL

#define FacLedControl_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   which_led,         1) \
X(a, STATIC,   SINGULAR, UENUM,    switch_state,      2) \
X(a, STATIC,   REPEATED, MESSAGE,  led_state,         3) \
X(a, STATIC,   SINGULAR, UENUM,    result,          100)
#define FacLedControl_CALLBACK NULL
#define FacLedControl_DEFAULT NULL
#define FacLedControl_led_state_MSGTYPE FacLedColor

#define FacBrushControl_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   ONEOF,    UENUM,    (value_item,brush_start,value_item.brush_start),   2) \
X(a, STATIC,   ONEOF,    UINT32,   (value_item,change_mode,value_item.change_mode),   3) \
X(a, STATIC,   SINGULAR, UENUM,    result,          100)
#define FacBrushControl_CALLBACK NULL
#define FacBrushControl_DEFAULT NULL

#define DataCollectParam_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    state,             1) \
X(a, STATIC,   SINGULAR, UINT32,   sampling_count,    2) \
X(a, STATIC,   SINGULAR, UINT32,   sampling_rate,     3) \
X(a, STATIC,   SINGULAR, UINT32,   upload_rate,       4)
#define DataCollectParam_CALLBACK NULL
#define DataCollectParam_DEFAULT NULL

#define FacDataCollectItem_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command_data,bat_vol,command_data.bat_vol),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command_data,pressure_sensor,command_data.pressure_sensor),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command_data,nine_axle,command_data.nine_axle),   4)
#define FacDataCollectItem_CALLBACK NULL
#define FacDataCollectItem_DEFAULT NULL
#define FacDataCollectItem_command_data_bat_vol_MSGTYPE DataCollectParam
#define FacDataCollectItem_command_data_pressure_sensor_MSGTYPE DataCollectParam
#define FacDataCollectItem_command_data_nine_axle_MSGTYPE DataCollectParam

#define FacCollectParam_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  param,             2) \
X(a, STATIC,   SINGULAR, UENUM,    result,          100)
#define FacCollectParam_CALLBACK NULL
#define FacCollectParam_DEFAULT NULL
#define FacCollectParam_param_MSGTYPE FacDataCollectItem

#define DataButtonParam_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    state,             1) \
X(a, STATIC,   SINGULAR, UENUM,    button_state_now,   2)
#define DataButtonParam_CALLBACK NULL
#define DataButtonParam_DEFAULT NULL

#define FacButtonItem_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command_data,power_button,command_data.power_button),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command_data,mode_button,command_data.mode_button),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command_data,press_mechanical,command_data.press_mechanical),   4)
#define FacButtonItem_CALLBACK NULL
#define FacButtonItem_DEFAULT NULL
#define FacButtonItem_command_data_power_button_MSGTYPE DataButtonParam
#define FacButtonItem_command_data_mode_button_MSGTYPE DataButtonParam
#define FacButtonItem_command_data_press_mechanical_MSGTYPE DataButtonParam

#define FacButtonState_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  button_state,      2) \
X(a, STATIC,   SINGULAR, UENUM,    result,          100)
#define FacButtonState_CALLBACK NULL
#define FacButtonState_DEFAULT NULL
#define FacButtonState_button_state_MSGTYPE FacButtonItem

#define FacWifiDemand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    wifi_speed,        1) \
X(a, STATIC,   SINGULAR, UINT32,   connect_command,   2) \
X(a, STATIC,   SINGULAR, UINT32,   connect_result,    3) \
X(a, STATIC,   SINGULAR, STRING,   ota_data,          4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  wifi_info,         5) \
X(a, STATIC,   SINGULAR, UINT32,   ota_result,        6) \
X(a, STATIC,   SINGULAR, UENUM,    result,          100)
#define FacWifiDemand_CALLBACK NULL
#define FacWifiDemand_DEFAULT NULL
#define FacWifiDemand_wifi_info_MSGTYPE FacWifiInfo

#define NineAlexData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   timestamp,         1) \
X(a, STATIC,   SINGULAR, UINT32,   acc_x,             2) \
X(a, STATIC,   SINGULAR, UINT32,   acc_y,             3) \
X(a, STATIC,   SINGULAR, UINT32,   acc_z,             4) \
X(a, STATIC,   SINGULAR, UINT32,   gyro_x,            5) \
X(a, STATIC,   SINGULAR, UINT32,   gyro_y,            6) \
X(a, STATIC,   SINGULAR, UINT32,   gyro_z,            7) \
X(a, STATIC,   SINGULAR, UINT32,   magnet_x,          8) \
X(a, STATIC,   SINGULAR, UINT32,   magnet_y,          9) \
X(a, STATIC,   SINGULAR, UINT32,   magnet_z,         10)
#define NineAlexData_CALLBACK NULL
#define NineAlexData_DEFAULT NULL

#define FacUploadNineAlex_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  data,              2) \
X(a, STATIC,   SINGULAR, UENUM,    result,          100)
#define FacUploadNineAlex_CALLBACK NULL
#define FacUploadNineAlex_DEFAULT NULL
#define FacUploadNineAlex_data_MSGTYPE NineAlexData

#define PresurceSensorItem_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   adc,               1) \
X(a, STATIC,   SINGULAR, UINT32,   value,             2)
#define PresurceSensorItem_CALLBACK NULL
#define PresurceSensorItem_DEFAULT NULL

#define PresurceSensorData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   timestamp,         1) \
X(a, STATIC,   SINGULAR, UINT32,   temperature,       2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  brush_head,        3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  mode_button,       4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  power_button,      5)
#define PresurceSensorData_CALLBACK NULL
#define PresurceSensorData_DEFAULT NULL
#define PresurceSensorData_brush_head_MSGTYPE PresurceSensorItem
#define PresurceSensorData_mode_button_MSGTYPE PresurceSensorItem
#define PresurceSensorData_power_button_MSGTYPE PresurceSensorItem

#define FacUploadPresSensor_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  sensor_data,       2) \
X(a, STATIC,   SINGULAR, UENUM,    result,          100)
#define FacUploadPresSensor_CALLBACK NULL
#define FacUploadPresSensor_DEFAULT NULL
#define FacUploadPresSensor_sensor_data_MSGTYPE PresurceSensorData

#define FacPreSensorCalibResult_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   brush_head_adc,    1) \
X(a, STATIC,   SINGULAR, UINT32,   mode_button_adc,   2) \
X(a, STATIC,   SINGULAR, UINT32,   power_button_adc,   3) \
X(a, STATIC,   SINGULAR, UINT32,   temperature,       4) \
X(a, STATIC,   SINGULAR, UENUM,    result,          100)
#define FacPreSensorCalibResult_CALLBACK NULL
#define FacPreSensorCalibResult_DEFAULT NULL

#define AccCaliData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    kx,                1) \
X(a, STATIC,   SINGULAR, FLOAT,    ky,                2) \
X(a, STATIC,   SINGULAR, FLOAT,    kz,                3) \
X(a, STATIC,   SINGULAR, FLOAT,    syx,               4) \
X(a, STATIC,   SINGULAR, FLOAT,    szx,               5) \
X(a, STATIC,   SINGULAR, FLOAT,    szy,               6) \
X(a, STATIC,   SINGULAR, FLOAT,    bx,                7) \
X(a, STATIC,   SINGULAR, FLOAT,    by,                8) \
X(a, STATIC,   SINGULAR, FLOAT,    bz,                9)
#define AccCaliData_CALLBACK NULL
#define AccCaliData_DEFAULT NULL

#define FacImuCalibResult_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   gyro_x,            1) \
X(a, STATIC,   SINGULAR, UINT32,   gyro_y,            2) \
X(a, STATIC,   SINGULAR, UINT32,   gyro_z,            3) \
X(a, STATIC,   SINGULAR, UINT32,   acc_x,             4) \
X(a, STATIC,   SINGULAR, UINT32,   acc_y,             5) \
X(a, STATIC,   SINGULAR, UINT32,   acc_z,             6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  new_cali,          7) \
X(a, STATIC,   SINGULAR, UENUM,    result,          100)
#define FacImuCalibResult_CALLBACK NULL
#define FacImuCalibResult_DEFAULT NULL
#define FacImuCalibResult_new_cali_MSGTYPE AccCaliData

#define FacSetTime_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   timestamp,         1) \
X(a, STATIC,   SINGULAR, UINT32,   timezone,          2)
#define FacSetTime_CALLBACK NULL
#define FacSetTime_DEFAULT NULL

#define FacSetBrushRecord_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   timestamp,         1) \
X(a, STATIC,   SINGULAR, UINT32,   plaque,            2) \
X(a, STATIC,   SINGULAR, BYTES,    work_time,         3) \
X(a, STATIC,   SINGULAR, BYTES,    pressure_time,     4) \
X(a, STATIC,   SINGULAR, BYTES,    horizon_brush,     5)
#define FacSetBrushRecord_CALLBACK NULL
#define FacSetBrushRecord_DEFAULT NULL

#define FacOtaFileInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   file_size,         1) \
X(a, STATIC,   SINGULAR, UINT32,   version_code,      2) \
X(a, STATIC,   SINGULAR, UINT32,   version_type,      3) \
X(a, STATIC,   SINGULAR, STRING,   url,               4) \
X(a, STATIC,   SINGULAR, STRING,   md5,               5)
#define FacOtaFileInfo_CALLBACK NULL
#define FacOtaFileInfo_DEFAULT NULL

#define FacInternetOta_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  file_info,         1) \
X(a, STATIC,   SINGULAR, UENUM,    result,          100)
#define FacInternetOta_CALLBACK NULL
#define FacInternetOta_DEFAULT NULL
#define FacInternetOta_file_info_MSGTYPE FacOtaFileInfo

extern const pb_msgdesc_t FactoryDataPackage_msg;
extern const pb_msgdesc_t FacGetDevBaseInfo_msg;
extern const pb_msgdesc_t FacDevState_msg;
extern const pb_msgdesc_t FacBatteryInfo_msg;
extern const pb_msgdesc_t FacWifiInfo_msg;
extern const pb_msgdesc_t FacDevInfoValue_msg;
extern const pb_msgdesc_t FacDevInfo_msg;
extern const pb_msgdesc_t FacGetPeriphState_msg;
extern const pb_msgdesc_t FacAgeingTest_msg;
extern const pb_msgdesc_t FacRegisterConfig_msg;
extern const pb_msgdesc_t FacLcdControl_msg;
extern const pb_msgdesc_t FacMotoParam_msg;
extern const pb_msgdesc_t ServoMotorParam_msg;
extern const pb_msgdesc_t FacMotoControl_msg;
extern const pb_msgdesc_t FacMotorCalibResult_msg;
extern const pb_msgdesc_t FacCameraControl_msg;
extern const pb_msgdesc_t FacLedColor_msg;
extern const pb_msgdesc_t FacLedControl_msg;
extern const pb_msgdesc_t FacBrushControl_msg;
extern const pb_msgdesc_t DataCollectParam_msg;
extern const pb_msgdesc_t FacDataCollectItem_msg;
extern const pb_msgdesc_t FacCollectParam_msg;
extern const pb_msgdesc_t DataButtonParam_msg;
extern const pb_msgdesc_t FacButtonItem_msg;
extern const pb_msgdesc_t FacButtonState_msg;
extern const pb_msgdesc_t FacWifiDemand_msg;
extern const pb_msgdesc_t NineAlexData_msg;
extern const pb_msgdesc_t FacUploadNineAlex_msg;
extern const pb_msgdesc_t PresurceSensorItem_msg;
extern const pb_msgdesc_t PresurceSensorData_msg;
extern const pb_msgdesc_t FacUploadPresSensor_msg;
extern const pb_msgdesc_t FacPreSensorCalibResult_msg;
extern const pb_msgdesc_t AccCaliData_msg;
extern const pb_msgdesc_t FacImuCalibResult_msg;
extern const pb_msgdesc_t FacSetTime_msg;
extern const pb_msgdesc_t FacSetBrushRecord_msg;
extern const pb_msgdesc_t FacOtaFileInfo_msg;
extern const pb_msgdesc_t FacInternetOta_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define FactoryDataPackage_fields &FactoryDataPackage_msg
#define FacGetDevBaseInfo_fields &FacGetDevBaseInfo_msg
#define FacDevState_fields &FacDevState_msg
#define FacBatteryInfo_fields &FacBatteryInfo_msg
#define FacWifiInfo_fields &FacWifiInfo_msg
#define FacDevInfoValue_fields &FacDevInfoValue_msg
#define FacDevInfo_fields &FacDevInfo_msg
#define FacGetPeriphState_fields &FacGetPeriphState_msg
#define FacAgeingTest_fields &FacAgeingTest_msg
#define FacRegisterConfig_fields &FacRegisterConfig_msg
#define FacLcdControl_fields &FacLcdControl_msg
#define FacMotoParam_fields &FacMotoParam_msg
#define ServoMotorParam_fields &ServoMotorParam_msg
#define FacMotoControl_fields &FacMotoControl_msg
#define FacMotorCalibResult_fields &FacMotorCalibResult_msg
#define FacCameraControl_fields &FacCameraControl_msg
#define FacLedColor_fields &FacLedColor_msg
#define FacLedControl_fields &FacLedControl_msg
#define FacBrushControl_fields &FacBrushControl_msg
#define DataCollectParam_fields &DataCollectParam_msg
#define FacDataCollectItem_fields &FacDataCollectItem_msg
#define FacCollectParam_fields &FacCollectParam_msg
#define DataButtonParam_fields &DataButtonParam_msg
#define FacButtonItem_fields &FacButtonItem_msg
#define FacButtonState_fields &FacButtonState_msg
#define FacWifiDemand_fields &FacWifiDemand_msg
#define NineAlexData_fields &NineAlexData_msg
#define FacUploadNineAlex_fields &FacUploadNineAlex_msg
#define PresurceSensorItem_fields &PresurceSensorItem_msg
#define PresurceSensorData_fields &PresurceSensorData_msg
#define FacUploadPresSensor_fields &FacUploadPresSensor_msg
#define FacPreSensorCalibResult_fields &FacPreSensorCalibResult_msg
#define AccCaliData_fields &AccCaliData_msg
#define FacImuCalibResult_fields &FacImuCalibResult_msg
#define FacSetTime_fields &FacSetTime_msg
#define FacSetBrushRecord_fields &FacSetBrushRecord_msg
#define FacOtaFileInfo_fields &FacOtaFileInfo_msg
#define FacInternetOta_fields &FacInternetOta_msg

/* Maximum encoded size of messages (where known) */
#define AccCaliData_size                         45
#define DataButtonParam_size                     4
#define DataCollectParam_size                    20
#define FacAgeingTest_size                       31
#define FacBatteryInfo_size                      14
#define FacBrushControl_size                     11
#define FacButtonItem_size                       8
#define FacButtonState_size                      83
#define FacCameraControl_size                    11
#define FacCollectParam_size                     211
#define FacDataCollectItem_size                  24
#define FacDevInfoValue_size                     114
#define FacDevInfo_size                          583
#define FacDevState_size                         7
#define FacGetDevBaseInfo_size                   115
#define FacGetPeriphState_size                   13
#define FacImuCalibResult_size                   86
#define FacInternetOta_size                      691
#define FacLcdControl_size                       19
#define FacLedColor_size                         20
#define FacLedControl_size                       187
#define FacMotoControl_size                      135
#define FacMotoParam_size                        17
#define FacMotorCalibResult_size                 135
#define FacOtaFileInfo_size                      341
#define FacPreSensorCalibResult_size             27
#define FacRegisterConfig_size                   12
#define FacSetBrushRecord_size                   66
#define FacSetTime_size                          12
#define FacUploadNineAlex_size                   933
#define FacUploadPresSensor_size                 843
#define FacWifiDemand_size                       189
#define FacWifiInfo_size                         110
#define FactoryDataPackage_size                  939
#define NineAlexData_size                        60
#define PresurceSensorData_size                  54
#define PresurceSensorItem_size                  12
#define ServoMotorParam_size                     22

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
